### ISSUE TITLE
Bazel does not build Python extension for fast protocol buffers

### ISSUE THREAD

**Issue by skearnes** [google/protobuf#1013]
I'm trying to get fast python protocol buffers working with TensorFlow: tensorflow/tensorflow#310.

The protobuf BUILD doesn't seem to include the pyext files at all, and running with `PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=cpp` gives errors like
```
Traceback (most recent call last):
  File "/cluster/home/kearnes/git/tensorflow/bazel-bin/deaps/util/view_examples.runfiles/deaps/util/view_examples.py", line 6, in <module>
    from google.protobuf import text_format
  File "/cluster/home/kearnes/git/tensorflow/bazel-bin/deaps/util/view_examples.runfiles/google/protobuf/text_format.py", line 53, in <module>
    from google.protobuf.internal import type_checkers
  File "/cluster/home/kearnes/git/tensorflow/bazel-bin/deaps/util/view_examples.runfiles/google/protobuf/internal/type_checkers.py", line 54, in <module>
    from google.protobuf.internal import decoder
  File "/cluster/home/kearnes/git/tensorflow/bazel-bin/deaps/util/view_examples.runfiles/google/protobuf/internal/decoder.py", line 90, in <module>
    from google.protobuf.internal import encoder
  File "/cluster/home/kearnes/git/tensorflow/bazel-bin/deaps/util/view_examples.runfiles/google/protobuf/internal/encoder.py", line 73, in <module>
    from google.protobuf.internal import wire_format
  File "/cluster/home/kearnes/git/tensorflow/bazel-bin/deaps/util/view_examples.runfiles/google/protobuf/internal/wire_format.py", line 36, in <module>
    from google.protobuf import descriptor
  File "/cluster/home/kearnes/git/tensorflow/bazel-bin/deaps/util/view_examples.runfiles/google/protobuf/descriptor.py", line 46, in <module>
    from google.protobuf.pyext import _message
ImportError: cannot import name _message
```

**Comment by skearnes** [comment]
Fixed by #1029
