### ISSUE TITLE
java.lang.UnsupportedOperationException: This is supposed to be overridden by subclasses.

### ISSUE THREAD

**Issue by padmanaik** [google/protobuf#1206]
Our projects was running successfully on lower version of protobuf-java-2.4.0 . Now we are planning to make it run on hadoop 2.6 on CDH 5.5 

But when we try to run it throws exception for protobuffer. I updraded it protobuf-java-2.5.0 but it started throwing the below exception

Execute task unit getFile with handler DFSTaskHandler and callable unit org.saarus.service.hadoop.dfs.DFSTaskHandler$1@625d5633
39378 [pool-1-thread-1] WARN org.apache.hadoop.util.NativeCodeLoader - Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
Task: null
java.lang.UnsupportedOperationException: This is supposed to be overridden by subclasses.
	at com.google.protobuf.GeneratedMessage.getUnknownFields(GeneratedMessage.java:180)
	at org.apache.hadoop.hdfs.protocol.proto.ClientNamenodeProtocolProtos$GetFileInfoRequestProto.getSerializedSize(ClientNamenodeProtocolProtos.java:30108)
	at com.google.protobuf.AbstractMessageLite.toByteString(AbstractMessageLite.java:49)
	at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.constructRpcRequest(ProtobufRpcEngine.java:149)
	at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:193)
	at com.sun.proxy.$Proxy24.getFileInfo(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.hadoop.io.retry.RetryInvocationHandler.invokeMethod(RetryInvocationHandler.java:164)
	at org.apache.hadoop.io.retry.RetryInvocationHandler.invoke(RetryInvocationHandler.java:83)
	at com.sun.proxy.$Proxy24.getFileInfo(Unknown Source)
	at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolTranslatorPB.getFileInfo(ClientNamenodeProtocolTranslatorPB.java:629)
	at org.apache.hadoop.hdfs.DFSClient.getFileInfo(DFSClient.java:1545)
	at org.apache.hadoop.hdfs.DistributedFileSystem.getFileStatus(DistributedFileSystem.java:820)
	at org.saarus.service.hadoop.dfs.DFSTaskHandler$1.doCall(DFSTaskHandler.java:32)
	at org.saarus.service.hadoop.dfs.DFSTaskHandler$1.doCall(DFSTaskHandler.java:27)
	at org.saarus.service.task.CallableTaskUnit.call(CallableTaskUnit.java:22)
	at org.saarus.service.task.CallableTask.call(CallableTask.java:43)
	at org.saarus.service.task.CallableTask.call(CallableTask.java:7)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:292)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)

**Comment by haberman** [comment]
Protobuf 2.5 requires that the generated protobuf classes were generated with the 2.5 protobuf compiler. I believe that this error indicates you are mixing the 2.5 protobuf library with generated code from an earlier protobuf version.

I think you're experiencing the same bug described here: https://issues.apache.org/jira/browse/HADOOP-9845

To fix this bug, you need to make sure that your generated code matches the protobuf library version. This may require upgrading Hadoop or any other libraries that include protobuf generated code.
