### ISSUE TITLE
build problem with cpp_implementation on 2.6.1

### ISSUE THREAD

**Issue by abhi1010** [google/protobuf#1375]
I am not not able to build v2.6.1 with **`cpp_implementation`** for a **virtual environment**. I think the problem may be due to the fact that I am trying to use a virtual environment - something that may not be common for installing protobuf itself. 
My steps are as follows:

```
# Create a virtual env first
export LD_LIBRARY_PATH=../src/.libs
virtualenv -p python /tmp/pp
source /tmp/pp/bin/activate

wget https://github.com/google/protobuf/releases/download/v2.6.1/protobuf-2.6.1.tar.gz
tar zxf *.gz
cd protobuf-2.6.1
./autogen.sh
./configure --prefix=/tmp/pp/
make•
make check
make install

cd python

python setup.py clean # the one from virtualenv
python setup.py build --cpp_implementation
python setup.py test --cpp_implementation
```

No matter how I try, I am always getting stuck at the following:

```
running build_ext
copying build/lib.linux-x86_64-2.7/google/protobuf/pyext/_message.so -> google/protobuf/pyext
Traceback (most recent call last):
  File "setup.py", line 200, in <module>
    "Protocol Buffers are Google's data interchange format.",
  File "/usr/lib64/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib64/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib64/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/tmp/pp/lib/python2.7/site-packages/setuptools/command/test.py", line 142, in run
    self.with_project_on_sys_path(self.run_tests)
  File "/tmp/pp/lib/python2.7/site-packages/setuptools/command/test.py", line 122, in with_project_on_sys_path
    func()
  File "/tmp/pp/lib/python2.7/site-packages/setuptools/command/test.py", line 163, in run_tests
    testRunner=self._resolve_as_ep(self.test_runner),
  File "/usr/lib64/python2.7/unittest/main.py", line 94, in __init__
    self.parseArgs(argv)
  File "/usr/lib64/python2.7/unittest/main.py", line 149, in parseArgs
    self.createTests()
  File "/usr/lib64/python2.7/unittest/main.py", line 158, in createTests
    self.module)
  File "/usr/lib64/python2.7/unittest/loader.py", line 130, in loadTestsFromNames
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/usr/lib64/python2.7/unittest/loader.py", line 115, in loadTestsFromName
    test = obj()
  File "~/pr/protobuf-2.6.1/python/setup.py", line 89, in MakeTestSuite
    import google.protobuf.pyext.descriptor_cpp2_test as descriptor_cpp2_test
ImportError: No module named descriptor_cpp2_test
```

I have not seen this error around though but since it is always getting stuck there, there has to be a reason for this.

**Comment by xfxyjwf** [comment]
You need to install protobuf C++ first. After "make check", did you "make install"?

**Comment by abhi1010** [comment]
Yes, I did do that in one of my trial runs. I have updated the steps too, above, to reflect that. Still the same error response.

**Comment by abhi1010** [comment]
I think I realize where the issue lies.
The python that I want to install it into, is a `virtualenv` whereas the installation is going to the system's python. When I change my last line from `python setup.py test --cpp_implementation` to **`/usr/bin/python`**`setup.py test --cpp_implementation` it works. I believe it should work from the same `virtualenv`

In the lines above, even though I simply call upon **`python setup.py`**, it must be noted that it is actually the `virtualenv` because I am executing `source /tmp/pp/bin/activate` as my third line.
