### ISSUE TITLE
Importing generated code from .proto file on windows 10, python3.5 gives error ImportError: cannot import name 'symbol_database'

### ISSUE THREAD

**Issue by lovesh** [google/protobuf#1382]
I downloaded protobuf binary version `protoc-3.0.0-beta-2-win32.zip` and added the path of `protoc.exe` to system path. Then i downloaded [protobuf-python-3.0.0-beta-2.zip](https://github.com/google/protobuf/releases/download/v3.0.0-beta-2/protobuf-python-3.0.0-beta-2.zip) and installed python library using `python setup.py build` and `python setup.py install`. After that i can generate the python code for `.proto` file by using `protoc -I=. --python_out=. sample.proto`. but if i try to use it, i get this error

```
>>> from sample_pb2 import *
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\someuser\sz\sample_pb2.py", line 9, in <module>
    from google.protobuf import symbol_database as _symbol_database
ImportError: cannot import name 'symbol_database'
>>>
```

I was able to use `protoc-3.0.0-beta-2` on Linux with python3.5 but its not working on Windows. I am new to windows environment so is there something else i need to do? Thanks

UPDATE: Using `python setup.py test` gives error 

```
running build_ext
Traceback (most recent call last):
  File "setup.py", line 222, in <module>
    ext_modules=ext_module_list,
  File "C:\Users\someuser\AppData\Local\Programs\Python\Python35\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "C:\Users\someuser\AppData\Local\Programs\Python\Python35\lib\distutils\dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "C:\Users\someuser\AppData\Local\Programs\Python\Python35\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "C:\Users\someuser\AppData\Local\Programs\Python\Python35\lib\site-packages\setuptools\command\test.py", line 142, in run
    self.with_project_on_sys_path(self.run_tests)
  File "C:\Users\someuser\AppData\Local\Programs\Python\Python35\lib\site-packages\setuptools\command\test.py", line 122, in with_project_on_sys_path
    func()
  File "C:\Users\someuser\AppData\Local\Programs\Python\Python35\lib\site-packages\setuptools\command\test.py", line 163, in run_tests
    testRunner=self._resolve_as_ep(self.test_runner),
  File "C:\Users\someuser\AppData\Local\Programs\Python\Python35\lib\unittest\main.py", line 93, in __init__
    self.parseArgs(argv)
  File "C:\Users\someuser\AppData\Local\Programs\Python\Python35\lib\unittest\main.py", line 140, in parseArgs
    self.createTests()
  File "C:\Users\someuser\AppData\Local\Programs\Python\Python35\lib\unittest\main.py", line 147, in createTests
    self.module)
  File "C:\Users\someuser\AppData\Local\Programs\Python\Python35\lib\unittest\loader.py", line 219, in loadTestsFromNames
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "C:\Users\someuser\AppData\Local\Programs\Python\Python35\lib\unittest\loader.py", line 219, in <listcomp>
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "C:\Users\someuser\AppData\Local\Programs\Python\Python35\lib\unittest\loader.py", line 190, in loadTestsFromName
    return self.loadTestsFromModule(obj)
  File "C:\Users\someuser\AppData\Local\Programs\Python\Python35\lib\site-packages\setuptools\command\test.py", line 37, in loadTestsFromModule
    tests.append(self.loadTestsFromName(submodule))
  File "C:\Users\someuser\AppData\Local\Programs\Python\Python35\lib\unittest\loader.py", line 153, in loadTestsFromName
    module = __import__(module_name)
  File "C:\Users\someuser\AppData\Local\Programs\Python\Python35\lib\site-packages\google\protobuf\internal\cpp_message.py", line 49
    import copyreg
                 ^
TabError: inconsistent use of tabs and spaces in indentation
```

**Comment by haberman** [comment]
Sorry for the very slow response on this. Are you still having this problem?
