### ISSUE TITLE
undefined method `this' for #<Gem::Specification:0x3ff7a18390cc protobuf-3.6.7>

### ISSUE THREAD

**Issue by benoittgt** [google/protobuf#1395]
Hello

With this `.proto` file : https://github.com/google/play-work/blob/426d4acbdf6c62f314a98edec93bf37376e66efc/emm-notifications/src/main/proto/emm_pubsub.proto

I get : 
```
$ protoc --ruby_out=. emm_pubsub.proto
/Users/bti/.rvm/rubies/ruby-2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/specification.rb:2162:in `method_missing': undefined method `this' for #<Gem::Specification:0x3ff7a18390cc protobuf-3.6.7> (NoMethodError)
	from /Users/bti/.rvm/rubies/ruby-2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/specification.rb:1057:in `find_active_stub_by_path'
	from /Users/bti/.rvm/rubies/ruby-2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:64:in `require'
	from /Users/bti/.rvm/gems/ruby-2.3.0@appaloosa/gems/protobuf-3.6.7/bin/protoc-gen-ruby:9:in `<top (required)>'
	from /Users/bti/.rvm/gems/ruby-2.3.0@appaloosa/bin/protoc-gen-ruby:22:in `load'
	from /Users/bti/.rvm/gems/ruby-2.3.0@appaloosa/bin/protoc-gen-ruby:22:in `<main>'
	from /Users/bti/.rvm/gems/ruby-2.3.0@appaloosa/bin/ruby_executable_hooks:15:in `eval'
	from /Users/bti/.rvm/gems/ruby-2.3.0@appaloosa/bin/ruby_executable_hooks:15:in `<main>'
--ruby_out: protoc-gen-ruby: Plugin failed with status code 1.
```

I'm using `google-protobuf (3.0.0.alpha.5.0.4)`

**Comment by xfxyjwf** [comment]
Where did you get the protoc-gen-ruby? You are probably using a third-party ruby implementation.

**Comment by benoittgt** [comment]
True I had before and other ruby implementation that I removed.
```

**Comment by xfxyjwf** [comment]
Yes, proto2 is not supported in ruby. It seems to me you haven't used any proto2 only features. Could you just change the syntax to proto3?

**Comment by benoittgt** [comment]
Thanks @xfxyjwf. I've made few changes to the proto file to switch to proto3. Few things were missing.

It's now properly working with the proto3 file. Thanks a lot.
