### ISSUE TITLE
Issue Float number in repeated message C#

### ISSUE THREAD

**Issue by PierEsc** [google/protobuf#1621]
Hello, 

When I use this proto file:

```
message SerialObject {
	int32 				id = 1; 	// Object id
	int32 				type = 2;
	int32				age = 3;	
	float				confiedance = 4; // 0.0 to 1.0
	int32 				track_time  = 5;
}
message SerialObjects {
	int32 	last_object_index = 1; 
	int32		number_of_objects = 2; 
	int32		timestamp = 3;
	repeated SerialObject objects = 4; 
}
```

from an C++ app to C# app, I get an error 

> Google.Protobuf.InvalidProtocolBufferException: While parsing a protocol message, the input ended unexpectedly in the middle of a field.  This could mean either than the input has been truncated or that an embedded message misreported its own length.
   at Google.Protobuf.CodedInputStream.RefillBuffer(Boolean mustSucceed)
   at Google.Protobuf.CodedInputStream.ReadRawByte()
   at Google.Protobuf.CodedInputStream.ReadRawLittleEndian64()
   at Google.Protobuf.CodedInputStream.ReadFloat()
   at SerialObject.MergeFrom(CodedInputStream input)
   at Google.Protobuf.CodedInputStream.ReadMessage(IMessage builder)
   at Google.Protobuf.FieldCodec.<>c__DisplayClass16_0`1.<ForMessage>b__0(CodedInputStream input)
   at Google.Protobuf.Collections.RepeatedField`1.AddEntriesFrom(CodedInputStream input, FieldCodec`1 codec)
   at SerialObjects.MergeFrom(CodedInputStream input)
   at Google.Protobuf.MessageExtensions.MergeFrom(IMessage message, Byte[] data)
   at Google.Protobuf.MessageParser`1.ParseFrom(Byte[] data)
   at TestCharpProtobuff3.MainPage.Update(String topic, Byte[] message)

> 
I have set data for all the fields. 
But If I send only int32 data, I can parse the message in the C# app. 

When I use Float field in the repeated message, only on C++ I also can read it. 

I have the same issue with the double. 

Any have a solution? 

Thanks

**Comment by xfxyjwf** [comment]
When you send the data from C++ to C#, the data is probably truncated accidentally. Could you verify the  serialized data size on both ends?

**Comment by sathishkumar** [comment]
We're also facing same issue from double value 0.0 while storing into hadoop using pig storage. 

Any solution?
