### ISSUE TITLE
javascript generated code doesn't work when you use dot in a file name and include it

### ISSUE THREAD

**Issue by itavy** [google/protobuf#1745]
i wrote 2 proto files (itavy.pkg1.proto and itavy.pkg2.proto)

``` javascript
syntax = "proto3";

package itavy.pkg1;

enum AppVersion {
  V_0_0_1 = 0;
  V_0_0_2 = 1;
};
```

``` javascript
syntax = "proto3";

package itavy.pkg2;

import "itavy.pkg1.proto";

message User {
  itavy.pkg1.AppVersion version = 1;
  string name = 2;
  string email = 3;
};
```

after i generate the js code `protoc itavy.pkg2.proto --js_out=import_style=commonjs,binary:protos`
it will create file protos/itavy.pkg2_pb.js 

``` javascript
$ head -12 protos/itavy.pkg2_pb.js 
/**
 * @fileoverview
 * @enhanceable
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var itavy.pkg1_pb = require('./itavy.pkg1_pb.js');
```

that last line will break if you try to run the script:

```
$ node protos/itavy.pkg2_pb.js 
/home/itavy/tmp/gproto/protos/itavy.pkg2_pb.js:12
var itavy.pkg1_pb = require('./itavy.pkg1_pb.js');
         ^
SyntaxError: Unexpected token .
    at Object.exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:513:28)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Function.Module.runMain (module.js:575:10)
    at startup (node.js:160:18)
    at node.js:456:3

```

**Comment by adam-26** [comment]
Why has this been closed? I don't believe its been fixed or is there a workaround? I continue to have this problem.

**Comment by adam-26** [comment]
@xfxyjwf, can you re-open this issue? If you read my comments above, i think this bug is easy to fix?

**Comment by acozzette** [comment]
@adam-26 That sounds reasonable to me to just replace the dot with an underscore. @haberman, what do you think?

**Comment by haberman** [comment]
Makes sense to me.
