### ISSUE TITLE
protobuf-test is dumping core on Solaris

### ISSUE THREAD

**Issue by dago** [google/protobuf#1755]
The protobuf-test is dumping core on Solaris.

```
[----------] 1 test from ZeroCopyStreamByteSinkTest
[ RUN      ] ZeroCopyStreamByteSinkTest.TestAllInputOutputPatterns
[       OK ] ZeroCopyStreamByteSinkTest.TestAllInputOutputPatterns (78 ms)
[----------] 1 test from ZeroCopyStreamByteSinkTest (78 ms total)

[----------] 68 tests from JsonStreamParserTest
[ RUN      ] JsonStreamParserTest.SimpleTrue
FAIL protobuf-test (exit status: 139)
```

The stack frame looks like this:

```
dam@unstable10x [global]:/home/dam/work/protobuf/src > pstack core | gc++filt 
core 'core' of 23220:   /home/dam/work/protobuf/src/.libs/protobuf-test
 fef59cde testing::internal::linked_ptr<testing::Expectation>::operator*() const (1, 804755c, 0, fef54394) + 10
 fef543a6 testing::Sequence::AddExpectation(testing::Expectation const&) const (1, 8047560, 7f, fe4d00aa) + 1c
 0911105e testing::internal::FunctionMockerBase<google::protobuf::util::converter::ObjectWriter* (google::protobuf::StringPiece, bool)>::AddNewExpectation(char const*, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::tr1::tuple<testing::Matcher<google::protobuf::StringPiece>, testing::Matcher<bool> > const&) (9fafbe0, 98f4574, 7f, 80475ac, 9fafc08, 98f4574) + be
 0910b6b8 testing::internal::MockSpec<google::protobuf::util::converter::ObjectWriter* (google::protobuf::StringPiece, bool)>::InternalExpectedAt(char const*, int, char const*, char const*) (9fafc04, 98f4574, 7f, 98f456a, 98f4624, 80476a4) + 144
 091058e8 google::protobuf::util::converter::ExpectingObjectWriter::RenderBool(google::protobuf::StringPiece, bool) (9fafe54, 98fcb74, 0, 1) + 108
 09135900 google::protobuf::util::converter::JsonStreamParserTest_SimpleTrue_Test::TestBody() (9fafb10, fe5b4dfe, 8047778, fe5be725) + 64
 fe5be75f void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (9fafb10, 11, 0, fe5ca2fb) + 45
 fe5b95ee void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (9fafb10, 11, 0, fe5ca2fb) + 39
 fe5a09a1 testing::Test::Run() (9fafb10, fe5dcbd0, 8047878, fe5a11e0) + b9
 fe5a1202 testing::TestInfo::Run() (9efb540, 0, 80478d8, fe5a18f0) + fc
 fe5a192f testing::TestCase::Run() (9efb5d0, a, 8047928, fe5a8524) + 103
 fe5a8564 testing::internal::UnitTestImpl::RunAllTests() (9f3ccd8, 9f3ccd8, fe5caa08, fe5bfadf) + 2d6
 fe5bfb19 bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (9f3ccd8, fe5a828e, 0, fe5caa24) + 45
 fe5ba53e bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (9f3ccd8, fe5a828e, 0, fe5caa24) + 39
 fe5a71a9 testing::UnitTest::Run() (fe5f1b40, 8047a44, 8047a18, fe9e0ffe) + b5
 fe9e1007 RUN_ALL_TESTS() (10, 8cd5930, 9f8349c, 8047a44, feffa910, 8047a24) + 20
 fe9e0f32 main     (8cd5930, 1, 8047a68) + 4f
 08cd5930 _start   (1, 8047b74, 0, 8047ba4, 8047bc8, 8047bdd) + 80
```

Detailed logs are available from our protobuf buildbot on Solaris:
  https://buildfarm.opencsw.org/buildbot/waterfall?category=protobuf
(x86 is fails to build right now due to  #1736)

The test fails both on Sparc and x86, so no endian-issue.

**Comment by xfxyjwf** [comment]
Sorry, but we don't have a Solaris system to test/debug this. It would be appreciated if you can help send us a pull request to fix the problem.

**Comment by dago** [comment]
I'm not sure my C++ foo is strong enough for this, but I can set up an account for you on our buildfarm if that helps:
  https://www.opencsw.org/extend-it/signup/to-upstream-maintainers/
We also have CI where I could set up an additional branch.

**Comment by iarebatman** [comment]
I just wanted to add that this same issue exists on OpenBSD 6.1 under amd64.
I'm reporting the same details to the protobuf google group as requested by the test suite.

**test-suite.log**
```
[----------] 70 tests from JsonStreamParserTest
[ RUN      ] JsonStreamParserTest.SimpleTrue
Segmentation fault (core dumped) 
FAIL protobuf-test (exit status: 139)
```

**Stack trace from core dump**
```
(gdb) bt
#0  0x00000cb218ab7d14 in testing::Sequence::AddExpectation () from ./.libs/libgmock.so.0.0
#1  0x00000caf7b43acfb in testing::internal::MockSpec<google::protobuf::util::converter::ObjectWriter* ()(google::protobuf::StringPiece, bool)>::InternalExpectedAt ()
   from /usr/ports/pobj/protobuf-3.2.0/build-amd64/src/.libs/protobuf-test
#2  0x00000caf7b440525 in google::protobuf::util::converter::ExpectingObjectWriter::RenderBool ()
   from /usr/ports/pobj/protobuf-3.2.0/build-amd64/src/.libs/protobuf-test
#3  0x00000caf7b45a3c6 in google::protobuf::util::converter::JsonStreamParserTest_SimpleTrue_Test::TestBody ()
   from /usr/ports/pobj/protobuf-3.2.0/build-amd64/src/.libs/protobuf-test
#4  0x00000cb2059dd271 in testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void> () from ./.libs/libgtest.so.0.0
#5  0x00000cb2059d394a in testing::Test::Run () from ./.libs/libgtest.so.0.0
#6  0x00000cb1f2b9a600 in ?? ()
#7  0x00000cb20fab6c00 in ?? ()
#8  0x00000cb23aab0bc0 in ?? ()
#9  0x00000cb2059d3a98 in testing::TestInfo::Run () from ./.libs/libgtest.so.0.0
#10 0x00000cb1bf4c1198 in ?? ()
#11 0x0000000000000001 in ?? ()
#12 0x00000cb25d7b1d00 in ?? ()
#13 0x00000cb20fab6c00 in ?? ()
#14 0x00000cb23aab0bc0 in ?? ()
#15 0x00000cb2059b70a0 in testing::TestCase::total_test_count () from ./.libs/libgtest.so.0.0
#16 0x0000015b484fe103 in ?? ()
#17 0x00000cb2059d3b75 in testing::TestCase::Run () from ./.libs/libgtest.so.0.0
#18 0x00000cb2059d3e88 in testing::internal::UnitTestImpl::RunAllTests () from ./.libs/libgtest.so.0.0
#19 0x0000079500000000 in ?? ()
#20 0x0000000100000000 in ?? ()
#21 0x00000cb1fe304a4e in _dl_bind (object=0x0, index=Variable "index" is not available.
) at /usr/src/libexec/ld.so/amd64/rtld_machine.c:357
#22 0x00000cb205afac48 in testing::internal::kStackTraceMarker () from ./.libs/libgtest.so.0.0
#23 0x0000000000000000 in ?? ()
```

**Comment by xfxyjwf** [comment]
Closing as this issue was opened for a while and it's not actionable for us. There isn't much we can do unless we can reproduce the issue on our testing environment. Feel free to open new issues or send us pull requests if you still see the issue with latest protobuf versions.
