### ISSUE TITLE
build problem with cpp_implementation on 2.6.1

### ISSUE THREAD

**Issue by o-lee** [google/protobuf#1807]
This issue is the same as #1375 (I'm using CentOS): 
```
import google.protobuf.pyext.descriptor_cpp2_test as descriptor_cpp2_test
ImportError: No module named descriptor_cpp2_test`
```
However `/usr/bin/pythonsetup.py test --cpp_implementation` did not solve my problem. Instead, I manually installed setuptools from link in the protobuf-2.6.1/python/README.txt. Then `sudo python setup.py clean` and `sudo python setup.py build` but got the following error:
```
Installed [..]/Downloads/protobuf-2.6.1/python/.eggs/google_apputils-0.4.2-py2.7.egg
Traceback (most recent call last):
  File "setup.py", line 200, in <module>
    "Protocol Buffers are Google's data interchange format.",
  File "/usr/lib64/python2.7/distutils/core.py", line 112, in setup
    _setup_distribution = dist = klass(attrs)
  File "build/bdist.linux-x86_64/egg/setuptools/dist.py", line 279, in __init__
  File "build/bdist.linux-x86_64/egg/setuptools/dist.py", line 323, in fetch_build_eggs
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 826, in resolve
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 1085, in best_match
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 695, in find
pkg_resources.VersionConflict: (pytz 2012d (/usr/lib/python2.7/site-packages), Requirement.parse('pytz>=2010'))
```
Found this [chat log](http://chat-logs.dcpython.org/day/pypa/2015-10-12) about above error and ran `sudo pip install pytz --upgrade` like they suggested.  Reran `sudo python setup.py build` and `sudo python setup.py google_test` with one error:
```
Testing reflection_test
[..]/Downloads/protobuf-2.6.1/python/.eggs/google_apputils-0.4.2-py2.7.egg/google/apputils/basetest.py:1617: RuntimeWarning: Trying to access flag test_tmpdir before flags were parsed. This will raise an exception in the future.
  if not os.path.isdir(FLAGS.test_tmpdir):
  File "setup.py", line 200, in <module>
    "Protocol Buffers are Google's data interchange format.",
  File "/usr/lib64/python2.7/distutils/core.py", line 152, in setup
    dist.run_commands()
  File "/usr/lib64/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib64/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "build/bdist.linux-x86_64/egg/setuptools/command/test.py", line 172, in run
    self.run_tests()
  File "[..]/Downloads/protobuf-2.6.1/python/.eggs/google_apputils-0.4.2-py2.7.egg/google/apputils/setup_command.py", line 157, in run_tests
    ok &= self._RunTestModule(file_path)
  File "[..]/Downloads/protobuf-2.6.1/python/.eggs/google_apputils-0.4.2-py2.7.egg/google/apputils/setup_command.py", line 133, in _RunTestModule
    basetest.main()
  File "[..]/Downloads/protobuf-2.6.1/python/.eggs/google_apputils-0.4.2-py2.7.egg/google/apputils/basetest.py", line 1464, in main
    _RunInApp(RunTests, args, kwargs)
  File "[..]/Downloads/protobuf-2.6.1/python/.eggs/google_apputils-0.4.2-py2.7.egg/google/apputils/basetest.py", line 1595, in _RunInApp
    app.really_start(main=Main)
  File "[..]/Downloads/protobuf-2.6.1/python/.eggs/google_apputils-0.4.2-py2.7.egg/google/apputils/app.py", line 220, in really_start
    sys.exit(main(argv))
  File "[..]/Downloads/protobuf-2.6.1/python/.eggs/google_apputils-0.4.2-py2.7.egg/google/apputils/basetest.py", line 1593, in Main
    function(argv, args, kwargs)
  File "[..]/Downloads/protobuf-2.6.1/python/.eggs/google_apputils-0.4.2-py2.7.egg/google/apputils/basetest.py", line 1617, in RunTests
    if not os.path.isdir(FLAGS.test_tmpdir):
  File "build/bdist.linux-x86_64/egg/gflags/flagvalues.py", line 390, in __getattr__
    traceback.print_stack()
ERROR:root:Trying to access flag test_tmpdir before flags were parsed.
Traceback (most recent call last):
  File "build/bdist.linux-x86_64/egg/gflags/flagvalues.py", line 391, in __getattr__
    raise exceptions.UnparsedFlagAccessError(error_message)
UnparsedFlagAccessError: Trying to access flag test_tmpdir before flags were parsed.
..................................................................s...............................................................................
----------------------------------------------------------------------
Ran 146 tests in 0.468s

OK (skipped=1)
```
But I was able to continue and run the final commands with no errors.
1. `sudo python setup.py test --cpp_implementation` 
2. `sudo python setup.py install --cpp_implementation`

My assumption is that I got an import error because setuptools was not installed to setup the namespace for the different modules. A hint that was the case is that for every `__init__.py` there was NOT a `__init__.pyc` in the `protobuf-2.6.1/python/google/protobuf` sub-directories.

**Comment by o-lee** [comment]
I did a `sudo uninstall` and then installed again. No errors.
```
$ ./autogen.sh
$ ./configure --prefix=/usr
$ sudo make
$ sudo make check
$ sudo make install
$ sudo ldconfig # refresh shared library cache
$ protoc --version
$ export PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=cpp
$ export PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION_VERSION=2
$ sudo python setup.py build
$ sudo python setup.py google_test
$ sudo python setup.py test --cpp_implementation
$ sudo python setup.py install --cpp_implementation
```

**Comment by o-lee** [comment]
@anandolee, @xfxyjwf I posted this as a FYI for all users that run into this problem in 2.6.1. The `protobuf-2.6.1/python/README.txt` states:
```If you do not have setuptools installed, note that it will be downloaded and installed automatically as soon as you run setup.py.```
But it is NOT downloaded or installed when I run the command `sudo python setup.py build`. **Even though the solution is document along with this issue**, this will continue being an issue for those that do not have setuptools installed.

**Comment by anandolee** [comment]
@o-lee Thanks to let us know this issue clear.
