### ISSUE TITLE
Got UnicodeDecodeError using 'utf-8', change to 'ISO-8859-1' don't have this issue

### ISSUE THREAD

**Issue by lqs4188980** [google/protobuf#1915]
Hi folks,

When I trying to decode a message, I got error "UnicodeDecodeError: 'utf-8' codec can't decode byte 0xae in position 2: 'utf-8' codec can't decode byte 0xae in position 2: invalid start byte in field: TelemetryField.string_value". 
So I searched solution and found if I use "ISO-8859-1" instead of "utf-8", problem gone.

Can someone tell me if this is a real issue or just related to my environment? Is it safe to do such change?
My working environment is RHEL 5.5 with python 3.4.1.
Thanks

Traceback:
```
>>> msg.ParseFromString(data)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/ws/qisli-sjc/xspeed_auto_repo/pyats/lib/python3.4/site-packages/protobuf-3.0.0-py3.4.egg/google/protobuf/message.py", line 185, in ParseFromString
    self.MergeFromString(serialized)
  File "/ws/qisli-sjc/xspeed_auto_repo/pyats/lib/python3.4/site-packages/protobuf-3.0.0-py3.4.egg/google/protobuf/internal/python_message.py", line 1082, in MergeFromString
    if self._InternalParse(serialized, 0, length) != length:
  File "/ws/qisli-sjc/xspeed_auto_repo/pyats/lib/python3.4/site-packages/protobuf-3.0.0-py3.4.egg/google/protobuf/internal/python_message.py", line 1118, in InternalParse
    pos = field_decoder(buffer, new_pos, end, self, field_dict)
  File "/ws/qisli-sjc/xspeed_auto_repo/pyats/lib/python3.4/site-packages/protobuf-3.0.0-py3.4.egg/google/protobuf/internal/decoder.py", line 612, in DecodeRepeatedField
    if value.add()._InternalParse(buffer, pos, new_pos) != new_pos:
  File "/ws/qisli-sjc/xspeed_auto_repo/pyats/lib/python3.4/site-packages/protobuf-3.0.0-py3.4.egg/google/protobuf/internal/python_message.py", line 1118, in InternalParse
    pos = field_decoder(buffer, new_pos, end, self, field_dict)
  File "/ws/qisli-sjc/xspeed_auto_repo/pyats/lib/python3.4/site-packages/protobuf-3.0.0-py3.4.egg/google/protobuf/internal/decoder.py", line 612, in DecodeRepeatedField
    if value.add()._InternalParse(buffer, pos, new_pos) != new_pos:
  File "/ws/qisli-sjc/xspeed_auto_repo/pyats/lib/python3.4/site-packages/protobuf-3.0.0-py3.4.egg/google/protobuf/internal/python_message.py", line 1118, in InternalParse
    pos = field_decoder(buffer, new_pos, end, self, field_dict)
  File "/ws/qisli-sjc/xspeed_auto_repo/pyats/lib/python3.4/site-packages/protobuf-3.0.0-py3.4.egg/google/protobuf/internal/decoder.py", line 612, in DecodeRepeatedField
    if value.add()._InternalParse(buffer, pos, new_pos) != new_pos:
  File "/ws/qisli-sjc/xspeed_auto_repo/pyats/lib/python3.4/site-packages/protobuf-3.0.0-py3.4.egg/google/protobuf/internal/python_message.py", line 1118, in InternalParse
    pos = field_decoder(buffer, new_pos, end, self, field_dict)
  File "/ws/qisli-sjc/xspeed_auto_repo/pyats/lib/python3.4/site-packages/protobuf-3.0.0-py3.4.egg/google/protobuf/internal/decoder.py", line 502, in DecodeField
    field_dict[key] = _ConvertToUnicode(buffer[pos:new_pos])
  File "/ws/qisli-sjc/xspeed_auto_repo/pyats/lib/python3.4/site-packages/protobuf-3.0.0-py3.4.egg/google/protobuf/internal/decoder.py", line 469, in _ConvertToUnicode
    return local_unicode(byte_str, 'utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xae in position 2: 'utf-8' codec can't decode byte 0xae in position 2: invalid start byte in field: TelemetryField.string_value```

**Comment by xfxyjwf** [comment]
The data contains invalid strings in a string field. You'd better fix the data instead.

**Comment by lqs4188980** [comment]
Thanks you for the reply! @xfxyjwf 
But I didn't see any error report when directly decode with protoc. Is protoc ignored those errors?
Thanks

**Comment by xfxyjwf** [comment]
Yes, protoc is using the C++ implementation and it is more lenient on this.
