### ISSUE TITLE
Java JsonFormat.printer().preservingProtoFieldNames() incompatible with Python google.protobuf.json_format.Parse()

### ISSUE THREAD

**Issue by fryingpanjoe** [google/protobuf#2029]
Yo!

Using `JsonFormat.printer().preservingProtoFieldNames()` to serialize Protobuf to JSON in Java can make the result incompatible with Python's `google.protobuf.json_format.Parse()`.

Example:

``` protobuf
// test.proto
syntax = "proto2";
message Test {
  optional int32 under_score = 1;
}
```

``` python
# test.py
import test_pb2
import google.protobuf.json_format
google.protobuf.json_format.Parse('{"under_score":1}', test_pb2.Test())
```

The Java code will generate the following JSON:

``` json
{
    "under_score": 1
}
```

while the Python parser expects the following JSON:

``` json
{
    "underScore": 1
}
```

which results in the following error:

```
Traceback (most recent call last):
  File "test.py", line 3, in <module>
    google.protobuf.json_format.Parse('{"under_score":1}', test_pb2.Test())
  File "/usr/local/lib/python2.7/site-packages/google/protobuf/json_format.py", line 332, in Parse
    parser.ConvertMessage(js, message)
  File "/usr/local/lib/python2.7/site-packages/google/protobuf/json_format.py", line 363, in ConvertMessage
    self._ConvertFieldValuePair(value, message)
  File "/usr/local/lib/python2.7/site-packages/google/protobuf/json_format.py", line 441, in _ConvertFieldValuePair
    raise ParseError(str(e))
google.protobuf.json_format.ParseError: Message type "Test" has no field named "under_score".
```

**Comment by xfxyjwf** [comment]
This is a known issue in python JSON support. We already fixed it in our internal code base but it won't be included in opensource util next minor release (version 3.1.x).

**Comment by fryingpanjoe** [comment]
Fantabulous, thank you!

**Comment by acozzette** [comment]
Let me close this because I believe it has been fixed now; if it's still a problem feel free to reopen this issue.
