### ISSUE TITLE
Problem Protobuf Runtime Installation with Python

### ISSUE THREAD

**Issue by anbai106** [google/protobuf#2258]
Hi, everyone, I install protocol buffers in my Mac os x, and I use anaconda python, to install the c++ complier, it seems being right installed, but when I follows the instruction from this site:
https://github.com/google/protobuf/tree/master/python
when i run python setup.py test and python setup.py test --cpp_implementation
I got an error: 

 ✘  ~/Hao/tutorial/gRPC/protocol_buffers/protobuf-3.1.0/python  python setup.py build --cpp_implementation
running build
running build_py
running build_ext
 ~/Hao/tutorial/gRPC/protocol_buffers/protobuf-3.1.0/python  python setup.py test --cpp_implementation
running test
running egg_info
writing requirements to protobuf.egg-info/requires.txt
writing protobuf.egg-info/PKG-INFO
writing namespace_packages to protobuf.egg-info/namespace_packages.txt
writing top-level names to protobuf.egg-info/top_level.txt
writing dependency_links to protobuf.egg-info/dependency_links.txt
reading manifest file 'protobuf.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no previously-included files found matching 'google/protobuf/internal/_.proto'
warning: no previously-included files matching '__test.py' found under directory 'google'
warning: no previously-included files matching '__test.proto' found under directory 'google'
warning: no previously-included files matching '_.dll' found anywhere in distribution
warning: no previously-included files matching '_.pyc' found anywhere in distribution
warning: no previously-included files matching '_.pyo' found anywhere in distribution
warning: no previously-included files matching '*.so' found anywhere in distribution
writing manifest file 'protobuf.egg-info/SOURCES.txt'
running build_ext
copying build/lib.macosx-10.6-x86_64-2.7/google/protobuf/pyext/_message.so -> google/protobuf/pyext
copying build/lib.macosx-10.6-x86_64-2.7/google/protobuf/internal/_api_implementation.so -> google/protobuf/internal
Traceback (most recent call last):
  File "setup.py", line 252, in <module>
    ext_modules=ext_module_list,
  File "/Users/junhao.wen/anaconda2/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/Users/junhao.wen/anaconda2/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/Users/junhao.wen/anaconda2/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/Users/junhao.wen/anaconda2/lib/python2.7/site-packages/setuptools-23.0.0-py2.7.egg/setuptools/command/test.py", line 170, in run
  File "/Users/junhao.wen/anaconda2/lib/python2.7/site-packages/setuptools-23.0.0-py2.7.egg/setuptools/command/test.py", line 191, in run_tests
  File "/Users/junhao.wen/anaconda2/lib/python2.7/unittest/main.py", line 94, in __init__
    self.parseArgs(argv)
  File "/Users/junhao.wen/anaconda2/lib/python2.7/unittest/main.py", line 149, in parseArgs
    self.createTests()
  File "/Users/junhao.wen/anaconda2/lib/python2.7/unittest/main.py", line 158, in createTests
    self.module)
  File "/Users/junhao.wen/anaconda2/lib/python2.7/unittest/loader.py", line 130, in loadTestsFromNames
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/Users/junhao.wen/anaconda2/lib/python2.7/unittest/loader.py", line 103, in loadTestsFromName
    return self.loadTestsFromModule(obj)
  File "/Users/junhao.wen/anaconda2/lib/python2.7/site-packages/setuptools-23.0.0-py2.7.egg/setuptools/command/test.py", line 39, in loadTestsFromModule
  File "/Users/junhao.wen/anaconda2/lib/python2.7/unittest/loader.py", line 100, in loadTestsFromName
    parent, obj = obj, getattr(obj, part)
AttributeError: 'module' object has no attribute 'any_test_pb2'

Is this because that I did not install Protocol Compiler successfully? I can not find the file libprotobuf.so in my system.

Can you give me any suggestions? I am quite new to protocol buffers and I think the installation guide that you created is not so clean to follow for different systems. 

So if you have any clues for the Mac installation, please tell me, I have posted an issue half a month ago, but got no answer, really need your help:)

Thanks in advance

**Comment by swangsc** [comment]
I have exactly same issue, why this ticket is closed without any explain?
