### ISSUE TITLE
JavaScript: Closure compilation at the advanced level (WIP)

### ISSUE THREAD

**Issue by lhecker** [google/protobuf#2303]
Hey @haberman!

I've recently found your [TODO](https://github.com/google/protobuf/blob/104723fccf4c9f7bf2398073e6b04390dcd2298a/js/gulpfile.js#L63-L64) and started adding those proper `@export` etc. annotations.

I'm actually nearly done now: All required annotations are added, the gulp file as well as the tests have been modified & fixed. The problem I now have is that you guys are using `goog.asserts`, which gets stripped out on the advanced closure level and there is no CLI switch to disable that.

So... What should be the way forward now? Should I simply copy/paste the required parts from `goog.asserts` into this project, write a modified closure-compiler CLI or simply drop all asserts in the dist release? 🙂

cc: @xfxyjwf 

P.S.: The size of the gzipped dist release is about 60% smaller (28kB vs. 11kB) and permanently (!) about 30-50% (!) faster without the asserts @ advanced level. So maybe if we continue dropping all non-essential asserts we could even gain a non-trivial speed improvement (or release a "fast" version alternatively).

**Comment by myitcv** [comment]
30-50% faster? That sounds fantastic. 

On that very subject, is there some way we can add Javascript benchmarks? 

Having some benchmarks prior your PR being merged @lhecker would then nicely showcase the improvements when they land.

Would also help to avoid situations like pre-release https://github.com/google/protobuf/issues/2117

Is there a general, language independent suite of benchmarks that could be used?

**Comment by lhecker** [comment]
@myitcv I'll port the [C++ benchmarks](https://github.com/google/protobuf/tree/master/benchmarks) to JS realy quick, but I'm not really comfortable with integrating it into this project since I'm not familar with the coding style, preferred directory layout, nor library/framework choice. I'll make it available as a gist or something though as soon as I'm done. 🙂

**Comment by lhecker** [comment]
@myitcv I've set up a [benchmark project](https://github.com/lhecker/protobuf-js-bench) (quick & dirty though).

Here are the numbers (formatted):

name                         | samples | ops/sec | ns/op   | rme
-----------------------------|---------|---------|---------|-------
`decode proto2 message1 old` |      93 | 169445  |    5902 | ±0.13%
`decode proto2 message1 new` |      95 | 348173  |    2872 | ±0.62%
`decode proto2 message2 old` |      75 |    135  | 7390579 | ±1.62%
`decode proto2 message2 new` |      83 |    202  | 4955115 | ±0.34%
`decode proto3 message1 old` |      95 | 119103  |    8396 | ±0.67%
`decode proto3 message1 new` |      95 | 195243  |    5122 | ±1.12%

And the less interesting part (encoding doesnt really use assertions):

name                         | samples | ops/sec | ns/op   | rme
-----------------------------|---------|---------|---------|-------
`encode proto2 message1 old` |      92 | 201252  |    4969 | ±0.85%
`encode proto2 message1 new` |      93 | 204008  |    4902 | ±0.80%
`encode proto2 message2 old` |      88 |    384  | 2603301 | ±1.10%
`encode proto2 message2 new` |      90 |    390  | 2566644 | ±0.81%
`encode proto3 message1 old` |      94 | 121750  |    8214 | ±0.83%
`encode proto3 message1 new` |      93 | 121377  |    8239 | ±0.92%

**Comment by myitcv** [comment]
Thanks for the update @lhecker - we'd be very happy to give this a try when you have a branch ready.

**Comment by lhecker** [comment]
@myitcv You can find it [here](https://github.com/lhecker/protobuf/tree/js-closure-advanced). 🙂

You can build it by running `gulp dist` in the `js` subfolder, which will generate a `google-protobuf.js` file there. It won't pass tests yet though since they rely on `goog.asserts` which are optimized away in my new branch. Alternatively you can use [this](https://raw.githubusercontent.com/lhecker/protobuf-js-bench/master/google-protobuf-new.js) file, which is exactly the same.

**Comment by myitcv** [comment]
@lhecker - I'm being slow; how does the `google-protobuf.js` that results from `gulp dist` correspond to the files that are distributed as part of a [JS release](https://github.com/google/protobuf/releases/download/v3.1.0/protobuf-js-3.1.0.tar.gz)?

**Comment by lhecker** [comment]
Ah okay I assumed you're using the npm/commonjs version (because most do nowadays, right?) and that particular file is what's distributed there. If you don't use that you can probably directly use my fork (I don't really see any difference between that JS release and the actual repository so I guess that should work).

**Comment by myitcv** [comment]
No, we're using the [official Github releases](https://github.com/google/protobuf/releases)

What's interesting is that the file `google-protobuf.js` is not included in the official release tarballs. 

Which makes me wonder whether we're doing the "right thing" or not...

We reference:

```html
<script src="goog/base.js"></script>
<script src="protobuf/map.js"></script>
<script src="protobuf/message.js"></script>
<script src="protobuf/binary/arith.js"></script>
<script src="protobuf/binary/constants.js"></script>
<script src="protobuf/binary/utils.js"></script>
<script src="protobuf/binary/decoder.js"></script>
<script src="protobuf/binary/encoder.js"></script>
<script src="protobuf/binary/reader.js"></script>
<script src="protobuf/binary/writer.js"></script>
```

where `goog/base.js` is a reference to the [latest closure-library](https://github.com/google/closure-library)

And the `protobuf/**/*.js` files are those distributed as part of the official protobuf releases as I mentioned above.

Any thoughts on where we're going wrong?

Should we be referencing the `google-protobuf.js` file? In which case, should it be part of the official release tarballs?

**Comment by lhecker** [comment]
No I think you should continue referencing the same files (but those from my fork instead). I didn't use anything except for CommonJS and ES6 modules in a long time so I'm not entirely sure about any implications regarding precompilation with the closure compiler etc. (I'm not even a real frontend engineer anyways).

The `google-protobuf.js` generated by `gulp dist` is a CommonJS module and used as the official [npm module](https://www.npmjs.com/package/google-protobuf). As such it uses `module.export` (like in node.js) and exports nothing to the global `window` object (which you're probably expecting if you use the JS files directly). If you'd use `google-protobuf.js` you'd need to use a browser bundler like Webpack.

**Comment by lhecker** [comment]
Ah btw @myitcv: I don't know how your asset compilation chain is set up or if you even have one but to make use of possible performance improvements due to the removal of the `goog.asserts` calls you'd need to use either the precompiled CommonJS module or compile the assets you listed above using the Closure Compiler like [this](https://github.com/lhecker/protobuf/blob/js-closure-advanced/js/gulpfile.js#L67-L80). Otherwise you'll always continue using the debug-by-default code.

**Comment by myitcv** [comment]
@lhecker thanks. It's been a while since we looked at our build pipeline... indeed when we first put it together there we no up-to-date npm packages for either the closure library or protobuf (hence my not having a clue about `google-protobuf.js`) so great to see that's moved on. I'll take a closer look over the next couple of days in order to try and exercise your optimisations.

**Comment by myitcv** [comment]
@lhecker after a very rudimentary test, we're also seeing ~40% speed up which is great, specifically around `deserializeBinaryFromReader`

**Comment by haberman** [comment]
Wow, this is great. Sorry for the delay, There is so much activity on GitHub that I miss stuff sometimes.

I think dropping asserts for the dist release should be fine. We want them to trigger in unit tests, but I think the intention is that release builds will not need them.

Please send a PR with your work -- this sounds great.

**Comment by lhecker** [comment]
@haberman Sorry I forgot about this again. 😕
But I took some time today to rebase my work onto the current master, which you can find [here](https://github.com/lhecker/protobuf/tree/js-closure-advanced).

There where quite some merge conflicts going on, but by carefully applying some [nuclear regular expressions](https://xkcd.com/208/) (as simple as `/\*\*\n((?!@export)(.|\n))+? \*\/\n[.\w]+?[^_] =`) it was easy to fix. 😂

Again: The problem is that throughout the code you guys currently use closure asserts as a way to add preconditions for functions, but unfortunately asserts get stripped away in optimized builds.

So my question in this issue remains: What do we do about the use of asserts in the code? [One example is this](https://github.com/lhecker/protobuf/blob/9e94cae1250cffea0dc5f3155f071c6227088a5c/js/message.js#L1494) which makes the [testCopyInto_notSameType](https://github.com/lhecker/protobuf/blob/9e94cae1250cffea0dc5f3155f071c6227088a5c/js/message_test.js#L525-L527) test fail. This is the only test that fails due to this, but there are surely more places in the code where asserts are used like that, but don't have any unit tests yet.

The other test that fails right now is [testUnknownExtension](https://github.com/lhecker/protobuf/blob/9e94cae1250cffea0dc5f3155f071c6227088a5c/js/binary/proto_test.js#L637), but I'm not yet entirely sure why it fails. This test creates a `new jspb.BinaryWriter();` which is *not* coming from the optimized `google-protobuf.js`, because if you dump the instance to the console it's structure looks like this:

```
writer { blocks_: [],
  totalLength_: 0,
  encoder_: { buffer_: [] },
  bookmarks_: [] }
```

while a `BinaryWriter` from the compiled version looks like this:

```
 V { f: [],
   b: 0,
   a: Xa { a: [] },
   g: [] }
```

I don't really understand all the code in this library, which is why it'd be great if someone can help me fix the remaining 2 tests.

Do you want me to still open a PR even though it's incomplete? Either way we have to decide what to do about the assertions (e.g. drop them including tests that rely on that behaviour entirely or replace them with `if (...) throw new Error()`) and how to solve the `testUnknownExtension` test. 🙂

**Comment by haberman** [comment]
> Again: The problem is that throughout the code you guys currently use closure asserts as a way to add preconditions for functions, but unfortunately asserts get stripped away in optimized builds.

I think this is entirely intended. The asserts are intended to catch errors in how the functions are called. But we only want to perform these checks in debug builds (ie. in unit tests). In optimized builds we don't want to pay for these checks.

How many of our unit tests depend on asserts getting triggered? Perhaps we could wrap these checks somehow so that they are only triggered for non-opt builds?

The other question is how we could allow our users to use the non-opt build for their own unit tests. Ideally the npm package could include both debug and release builds, and users could opt for which one they want. Does that seem doable?

**Comment by AndrewGuenther** [comment]
ping @lhecker would love to see these changes land.

Looking at your WIP branch it wasn't immediately clear, do these changes only apply to the `google-protobuf` module, or would these options be available through `protoc` as well?

**Comment by lhecker** [comment]
@AndrewGuenther I currently don't have enough time to work on this and I'm not sure when this will change: I recently switched to compiling the output of `protoc` with the `js` source of protobuf by using the closure compiler directly (producing a very compact output). This achieves an even slightly better result compared to my fork.

The WIP branch (`js-closure-advanced`) only applies to the `google-protobuf` module on npm as well as the output you get when compiling from the source directly (like me above). The JS code generated by `protoc` is already fully compatible with closure's advanced optimization level and no further options are needed there. Or did I possibly misunderstand your question?

**Comment by lhecker** [comment]
@haberman As I said in my previous comment I'm currently extremely busy and don't know when I'm able to continue my work. I hope you can understand that as well. 😅

The asserts might be a must have for the npm module though as that one won't have any closure type annotations etc. It'd might indeed be a good idea to ship a debug and a release build there due to that. I don't think there is an easy solution for switching between both though. A user of the npm package would have to code an own solution for that using a build script etc.

Also regarding the tests relying on asserts: I'm only aware of [testCopyInto_notSameType](https://github.com/lhecker/protobuf/blob/9e94cae1250cffea0dc5f3155f071c6227088a5c/js/message_test.js#L525-L527) and [testUnknownExtension](https://github.com/lhecker/protobuf/blob/9e94cae1250cffea0dc5f3155f071c6227088a5c/js/binary/proto_test.js#L637) relying on that. I went into a bit into detail in [my other comment above](https://github.com/google/protobuf/issues/2303#issuecomment-267603667).

**Comment by AndrewGuenther** [comment]
@lhecker that makes sense, I actually ended up going a similar route as well, however, when I directly compile the `protoc` output, none of the exported symbols seem to exist. Did you run into any issues with this?

Currently, I have to compile the entirety of each consuming project together in order to make it work, but ideally I would like to only compile the `protoc` output.

**Comment by lhecker** [comment]
@AndrewGuenther Did you make sure to use the `--export_local_property_definitions` and `--generate_exports` flags when calling the closure compiler? Otherwise exported properties won't actually be exported in the advanced level.

The relevant parts in my build script look like this:

```bash
if [ ! -r "$deps_path" ]; then
	echo $'\n# Calcdeps'
	./node_modules/google-closure-library/closure/bin/calcdeps.py \
		-p "$tmp_dir" \
		-p ./node_modules/google-closure-library/closure \
		-i "$gen_proto_path" \
		-i "./build_add_exports_es6.js" \
		> "$deps_path"
fi

readarray -t deps < "$deps_path"

java -jar "$compiler_path" \
	--warning_level=VERBOSE \
	--jscomp_error='*' \
	--jscomp_off=analyzerChecks \
	--jscomp_off=deprecated \
	--jscomp_off=extraRequire \
	--jscomp_off=inferredConstCheck \
	--jscomp_off=lintChecks \
	--jscomp_off=unnecessaryCasts \
	--compilation_level=ADVANCED \
	--process_common_js_modules \
	--assume_function_wrapper \
	--language_in=ECMASCRIPT5 \
	--language_out=ECMASCRIPT5 \
	--generate_exports \
	--export_local_property_definitions \
	--rewrite_polyfills=false \
	--create_source_map="$out_map_path" \
	--js_output_file="$out_js_path" \
	"${deps[@]}"
```

The extra call to `calcdeps.py` is needed in my case because I'm also using [`clutz`](https://github.com/angular/clutz), which needs a list of input files to generate a .d.ts file for TypeScript. If that's not needed you can add [this](https://github.com/lhecker/protobuf/blob/js-closure-advanced/js/gulpfile.js#L78-L80) instead of having `"${deps[@]}"`.

**Comment by jjbubudi** [comment]
Merry Christmas everyone!

Looks like this went quiet for quite a while but it will be very useful to have it fixed. I've raised PR #5509 for this though I have trouble running tests locally...it keeps complaining with or without my change:
```
/path/to/protobuf/js/testproto_libs1.js:1997
proto.jspb.exttest.reverse.TestExtensionReverseOrderMessage2.extensionsBinary[2] = new jspb.ExtensionFieldBinaryInfo(
                                                                                 ^

TypeError: Cannot set property '2' of undefined
    at Object.<anonymous> (/Users/Jimmy/Development/protobuf/js/testproto_libs1.js:1997:82)
    at Module._compile (internal/modules/cjs/loader.js:721:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:732:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Module.require (internal/modules/cjs/loader.js:657:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at /Users/Jimmy/Development/protobuf/js/node_modules/jasmine/lib/jasmine.js:77:5
    at Array.forEach (<anonymous>)
```
I was using MacOS Mojave + node v11.5.0 + protoc v3.6.1 but switching back to node v6/v8 didn't help. Is anyone seeing the errors locally? If so please let me know how you resolved it. I can help look at which tests need to be updated.

**Comment by lhecker** [comment]
Oh dear... I'm such an idiot... I seem to have deleted my protobuf fork at some point since opening this issue and my work from back then has been lost. 😰
Thanks for picking up on this though, @jjbubudi! #5509 looks really nice. 🙂

**Comment by jjbubudi** [comment]
@lhecker Your commit is still here (referenced in this issue) :)
https://github.com/lhecker/protobuf/commit/9e94cae1250cffea0dc5f3155f071c6227088a5c
But the branch itself is gone so I have trouble finding out which commit is modifying the tests.

**Comment by jjbubudi** [comment]
After further modifications the only failing test is [testCopyInto_notSameType](https://github.com/protocolbuffers/protobuf/blob/master/js/message_test.js#L558-L560) which depends on `goog.asserts` being available even after compilation. To fix it properly might require some not-so-trivial code or build script changes.

**Comment by dhlolo** [comment]
Is there any progress? Seem jj's PR is not merged, and proto.js is still too large for mobile cases.
