### ISSUE TITLE
process hang before main function

### ISSUE THREAD

**Issue by vinllen** [google/protobuf#2328]
Hi, All,

I meet a problem that process hang before main function start, the gdb trace lists below:
```
(gdb) bt
#0  0x00007ffff3aeed27 in sched_yield ()
    at ../sysdeps/unix/syscall-template.S:81
#1  0x00000000004a7465 in google::protobuf::GoogleOnceInitImpl(long*, google::protobuf::Closure*) ()
#2  0x00000000004d6f54 in google::protobuf::FileDescriptorProto::SharedCtor()
    ()
#3  0x00000000004dffe7 in google::protobuf::FileDescriptorProto::FileDescriptorProto() ()
#4  0x00000000004ec4f5 in google::protobuf::EncodedDescriptorDatabase::Add(void const*, int) ()
#5  0x00000000004aef7a in google::protobuf::DescriptorPool::InternalAddGeneratedFile(void const*, int) ()
#6  0x00007ffff4c74f33 in protobuf_AddDesc_CpuInfo_2eproto() ()
   from /pica/lib/libpbdata.so.0
#7  0x00007ffff4c767b9 in StaticDescriptorInitializer_CpuInfo_2eproto::StaticDescriptorInitializer_CpuInfo_2eproto() () from /pica/lib/libpbdata.so.0
#8  0x00007ffff4c7644d in ?? () from /pica/lib/libpbdata.so.0
#9  0x00007ffff4c76462 in ?? () from /pica/lib/libpbdata.so.0
#10 0x00007ffff7dea9ba in call_init (l=<optimized out>, argc=argc@entry=1,
    argv=argv@entry=0x7fffffffecc8, env=env@entry=0x7fffffffecd8)
    at dl-init.c:78
#11 0x00007ffff7deaaa3 in call_init (env=0x7fffffffecd8, argv=0x7fffffffecc8,
    argc=1, l=<optimized out>) at dl-init.c:36
#12 _dl_init (main_map=0x7ffff7ffe1a8, argc=1, argv=0x7fffffffecc8,
    env=0x7fffffffecd8) at dl-init.c:126
#13 0x00007ffff7ddd1ca in _dl_start_user () from /lib64/ld-linux-x86-64.so.2
#14 0x0000000000000001 in ?? ()
#15 0x00007fffffffeeba in ?? ()
#16 0x0000000000000000 in ?? ()
```
It looks that host execute `sched_yield` in GoogleOnceInitImpl. This issue occures when I move my code from MIPS into X86. I've no idea whether should enable GOOGLE_PROTOBUF_NO_THREAD_SAFETY in my Makefile, honestly, I tried but failed both.

**Comment by vinllen** [comment]
My protobuf version if 2.6.1

**Comment by vinllen** [comment]
Disable this macro is OK in X86. But I am still confusing about why should enable this in MIPS

**Comment by pherl** [comment]
This macro should only be enabled if your platform is single threaded, in which case skip all the thread synchronization calls. It also enables the compilation in these platforms as they don't have locks, atomicops etc.

In X86 there will be deadlocks if you set the macro.
