### ISSUE TITLE
using java.util.logging.Logger may cause ClassNotFound in javaagent for JBoss

### ISSUE THREAD

**Issue by wu-sheng** [google/protobuf#2339]
I am developing a javaagent project, as a instrument of JBoss 8.0 . 
I use protobuf 3.0.0, the manifest info is following:
```properties
Manifest-Version: 1.0
Bnd-LastModified: 1469731108499
Build-Jdk: 1.8.0_45
Built-By: root
Bundle-Description: Core Protocol Buffers library. Protocol Buffers are 
 a way of encoding structured data in an    efficient yet extensible for
 mat.
Bundle-DocURL: https://developers.google.com/protocol-buffers/
Bundle-License: http://www.opensource.org/licenses/bsd-license.php
Bundle-ManifestVersion: 2
Bundle-Name: Protocol Buffers [Core]
Bundle-SymbolicName: com.google.protobuf
Bundle-Vendor: Google
Bundle-Version: 3.0.0
Created-By: Apache Maven Bundle Plugin
Export-Package: com.google.protobuf;version="3.0.0"
Import-Package: com.google.protobuf;version="[3.0,4)",sun.misc
Require-Capability: osgi.ee;filter:="(&(osgi.ee=JavaSE)(version=1.6))"
Tool: Bnd-3.0.0.201509101326
```

When I use `map<int32,string>` defined a field, and use `putAll` method. Somehow, class `Descriptors` is loaded by classloader. And this trigger `Logger.getLogger(Descriptors.class.getName())`. 
As we known, `LogManager` is necessary for java.util.logging.* . The static block of `LogManager` is using `System.getProperty("java.util.logging.manager")` to init. 
In JBOSS, it will set `java.util.logging.manager` to a JBOSS class. So, when I run code in premain, I can't access to the **LogManager**, it trigger ClassNotFound.

I recommend **protobuf** not use this java.util.logging.

**Comment by xfxyjwf** [comment]
What would be a good alternative to java.util.logging?

**Comment by wu-sheng** [comment]
I recommend not to use `java.util.logging` directly. I think the better way to create a **LogResolver** in grpc-java. **LogResolver** will only choose `java.util.logging` as default logger, and provide api to set other implements. 
And the most important, **LogResolver** should not trigger **ClassLoader** to load `java.util.logging`.

Does this seem good to you? 
If you are agree with me, I want to send a pull request to fix this problem. And we discuss further in that rp?

**Comment by wu-sheng** [comment]
I also create this issue in grpc-java project.
link: https://github.com/grpc/grpc-java/issues/2415

**Comment by xfxyjwf** [comment]
This really sounds like a JBOSS problem rather than a protobuf one. Protobuf uses standard logging facility but JBOSS does not support it well. I would rather not put any workaround in protobuf for a JBOSS bug.

**Comment by wu-sheng** [comment]
I am pretty sure this is a JBoss bug in my case. And JBoss project is out-of-service, so I will solve this use other ways.
On the other way, Is it necessary that protobuf use more elegant way to use logging? let protobuf work more robust?

**Comment by xfxyjwf** [comment]
If there is an alternative standard way (Java standard or Google standard) for logging, we can change the code to that, but what you proposed does not seem like a standard practice.

**Comment by wu-sheng** [comment]
Unfortunately, for now, I have not found any standard way. It seems the implement is not care of this scenario. 😭

**Comment by wu-sheng** [comment]
@xfxyjwf 
another issue occured:
```java
Nov 11, 2016 09:58:11:361 +0800 [8978524 181] com.blueware FINER: An error occurred calling Transaction.tracerFinished() for class web
logic.wsee.deploy.ServletDeployListener : java.lang.ExceptionInInitializerError
java.lang.ExceptionInInitializerError: null
        at java.lang.J9VMInternals.initialize(J9VMInternals.java:222) ~[na:1.6.0]
        at com.blueware.deps.com.google.protobuf.MapField.mergeFrom(MapField.java:204) ~[oneapm.jar:2.0]
        at com.blueware.monitor.collector.grpc.TransactionRecord$Builder.mergeFrom(TransactionRecord.java:1323) ~[oneapm.jar:2.0]
        at com.blueware.monitor.collector.grpc.TransactionRecord.toBuilder(TransactionRecord.java:1062) ~[oneapm.jar:2.0]
        at com.blueware.monitor.transaction.TransactionDataCompressorFactoryService.compressMetaData(TransactionDataCompressorFactoryS
ervice.java:401) ~[oneapm.jar:2.0]
        at com.blueware.monitor.transaction.TransactionDataCompressorFactoryService.compress(TransactionDataCompressorFactoryService.j
        at weblogic.deploy.internal.targetserver.BasicDeployment.activateFromServerLifecycle(BasicDeployment.java:361) [weblogic.jar:1
0.3.6.0]
```

why `MapField.mergeFrom` failured?

**Comment by wu-sheng** [comment]
cause by
```java
Caused by: java.lang.UnsupportedOperationException: null
        at com.blueware.deps.com.google.protobuf.MapFieldLite.ensureMutable(MapFieldLite.java:221) ~[oneapm.jar:2.0]
        at com.blueware.deps.com.google.protobuf.MapFieldLite.putAll(MapFieldLite.java:99) ~[oneapm.jar:2.0]
        at java.util.LinkedHashMap.<init>(LinkedHashMap.java:112) ~[na:na]
        at com.blueware.deps.com.google.protobuf.MapFieldLite.<init>(MapFieldLite.java:56) ~[oneapm.jar:2.0]
        at com.blueware.deps.com.google.protobuf.MapFieldLite.<clinit>(MapFieldLite.java:61) ~[oneapm.jar:2.0]
        at java.lang.J9VMInternals.initializeImpl(Native Method) ~[na:1.6.0]
        at java.lang.J9VMInternals.initialize(J9VMInternals.java:200) ~[na:1.6.0]
```

codes run fine in other jvm. why j9 fails?

**Comment by wu-sheng** [comment]
link to new issue:https://github.com/google/protobuf/issues/2356

**Comment by VenkRang** [comment]
@wu-sheng I am facing similar issue while using protobuf in my java agent. How did you get this solved?
