### ISSUE TITLE
JavaScript: "Assertion Error: Failure: Decoder hit an error" protoc-plugin

### ISSUE THREAD

**Issue by steckel** [google/protobuf#2354]
I have a protoc-plugin using the google-protobuf npm module and am encountering this assertion error at the strangest time. This happens in any use of the google-protobuf runtime interacting with protoc, so it's not my plugin necessarily.

Long story short, I get the following error thrown at Runtime unless I rename a specific field from a three character name to one or two. This shouldn't matter to the runtime creating a `CodeGeneratorRequest` so why could it be throwing here?  

```diff
 message Foo {
-  int32 bar = 1;
+  int32 ba = 1;
 }
```

```
goog.string.splitLimit=function(a,b,c){a=a.split(b);for(var d=[];0<c&&a.length;)d.push(a.shift()),c--;a.length&&d.push(a.join(b));return d};goog.string.editDistance=function(a,b){var c=[],d=[];if(a==b)return 0;if(!a.length||!b.length)return Math.max(a.length,b.length);for(var e=0;e<b.length+1;e++)c[e]=e;for(e=0;e<a.length;e++){d[0]=e+1;for(var f=0;f<b.length;f++)d[f+1]=Math.min(d[f]+1,c[f+1]+1,c[f]+Number(a[e]!=b[f]));for(f=0;f<c.length;f++)c[f]=d[f]}return d[b.length]};goog.asserts={};goog.asserts.ENABLE_ASSERTS=goog.DEBUG;goog.asserts.AssertionError=function(a,b){b.unshift(a);goog.debug.Error.call(this,goog.string.subs.apply(null,b));b.shift();this.messagePattern=a};goog.inherits(goog.asserts.AssertionError,goog.debug.Error);goog.asserts.AssertionError.prototype.name="AssertionError";goog.asserts.DEFAULT_ERROR_HANDLER=function(a){throw a;};goog.asserts.errorHandler_=goog.asserts.DEFAULT_ERROR_HAND
AssertionError: Failure: Decoder hit an error
    at new goog.asserts.AssertionError (/Users/.../node_modules/google-protobuf/google-protobuf.js:62:603)
    at Object.goog.asserts.fail (/Users/.../node_modules/google-protobuf/google-protobuf.js:64:89)
    at jspb.BinaryReader.nextField (/Users/.../node_modules/google-protobuf/google-protobuf.js:235:123)
    at Function.proto.google.protobuf.compiler.CodeGeneratorRequest.deserializeBinaryFromReader (/Users/.../node_modules/google-protobuf/google/protobuf/compiler/plugin_pb.js:103:17)
    at Function.proto.google.protobuf.compiler.CodeGeneratorRequest.deserializeBinary (/Users/.../node_modules/google-protobuf/google/protobuf/compiler/plugin_pb.js:91:62)
    at generateCode (/Users/.../node_modules/protoc-gen-flow/bin/protoc-gen-flow:42:259)
    at Socket.<anonymous> (/Users/.../node_modules/protoc-gen-flow/bin/protoc-gen-flow:42:1207)
    t emitNone (events.js:86:13)
    at Socket.emit (events.js:185:7)
    at emitReadable_ (_stream_readable.js:433:10)
```

**Comment by steckel** [comment]
This was due to my naive stdin stream reading. Closing.
