### ISSUE TITLE
Map causes java.lang.ExceptionInInitializerError: null in J9VM

### ISSUE THREAD

**Issue by wu-sheng** [google/protobuf#2356]
Here is my proto:
```proto
message TransactionRecord {
……
    map<string, string> parameters = 19;
……
}
```

Then, I use following code to get a builder
```java
final TransactionRecord.Builder metaDataBuilder = requestBuilder.getMetaData().toBuilder();
```

This code run fine in many JVMs, but fail in J9VM

Exception as following:
```
java.lang.ExceptionInInitializerError: null
        at java.lang.J9VMInternals.initialize(J9VMInternals.java:222) ~[na:1.6.0]
        at com.blueware.deps.com.google.protobuf.MapField.mergeFrom(MapField.java:204) ~[oneapm.jar:2.0]
        at com.blueware.monitor.collector.grpc.TransactionRecord$Builder.mergeFrom(TransactionRecord.java:1323) ~[oneapm.jar:2.0]
        at com.blueware.monitor.collector.grpc.TransactionRecord.toBuilder(TransactionRecord.java:1062) ~[oneapm.jar:2.0]
        at com.blueware.monitor.transaction.TransactionDataCompressorFactoryService.compressMetaData(TransactionDataCompressorFactoryS
ervice.java:401) ~[oneapm.jar:2.0]
        at com.blueware.monitor.transaction.TransactionDataCompressorFactoryService.compress(TransactionDataCompressorFactoryService.j
        at weblogic.deploy.internal.targetserver.BasicDeployment.activateFromServerLifecycle(BasicDeployment.java:361) [weblogic.jar:1
0.3.6.0]
        at weblogic.management.deploy.internal.ConfiguredDeployments.deployPreStandbyInternalApps(ConfiguredDeployments.java:85) [webl
ogic.jar:10.3.6.0]
        at weblogic.management.deploy.internal.DeploymentServerService.deployPreStandbyInternalApps(DeploymentServerService.java:168)
[weblogic.jar:10.3.6.0]
        at weblogic.management.deploy.internal.DeploymentPreStandbyServerService.start(DeploymentPreStandbyServerService.java:27) [web
logic.jar:10.3.6.0]
        at weblogic.t3.srvr.SubsystemRequest.run(SubsystemRequest.java:64) [weblogic.jar:10.3.6.0]
        at weblogic.work.ExecuteThread.execute(ExecuteThread.java:256) [com.bea.core.weblogic.workmanager_1.11.0.0.jar:1.11.0.0]
        at weblogic.work.ExecuteThread.run(ExecuteThread.java:221) [com.bea.core.weblogic.workmanager_1.11.0.0.jar:1.11.0.0]
Caused by: java.lang.UnsupportedOperationException: null
        at com.blueware.deps.com.google.protobuf.MapFieldLite.ensureMutable(MapFieldLite.java:221) ~[oneapm.jar:2.0]
        at com.blueware.deps.com.google.protobuf.MapFieldLite.putAll(MapFieldLite.java:99) ~[oneapm.jar:2.0]
        at java.util.LinkedHashMap.<init>(LinkedHashMap.java:112) ~[na:na]
        at com.blueware.deps.com.google.protobuf.MapFieldLite.<init>(MapFieldLite.java:56) ~[oneapm.jar:2.0]
        at com.blueware.deps.com.google.protobuf.MapFieldLite.<clinit>(MapFieldLite.java:61) ~[oneapm.jar:2.0]
        at java.lang.J9VMInternals.initializeImpl(Native Method) ~[na:1.6.0]
        at java.lang.J9VMInternals.initialize(J9VMInternals.java:200) ~[na:1.6.0]
        ... 45 common frames omitted
```

I have tried to remove `map parameters` for define, it goes fine. 
Is this a bug for map?
@xfxyjwf

**Comment by wu-sheng** [comment]
Instead, I use `final TransactionRecord.Builder metaDataBuilder = requestBuilder.getMetaDataBuilder();`, that can fix this issue.

How did this bug happen?

**Comment by wu-sheng** [comment]
@xfxyjwf , My teammate found there is a different implement in`LinkedHashMap`, which will trigger this bug.
Is the RP good enough for GRPC-java?

**Comment by xfxyjwf** [comment]
That change looks good to me. Already merged.

@D3Hunter

**Comment by wu-sheng** [comment]
@xfxyjwf . Thanks, I will look forward the next release, and we will be able to use map again. It will be very helpful. ^_^
