### ISSUE TITLE
C# ToString() on a message fails with an exception 

### ISSUE THREAD

**Issue by dibyendumajumdar** [google/protobuf#2405]
Hi

I am facing a problem when trying to invoke ToString() on a message. The following exception is thrown. I think this may be because my enum has allow_alias set to true, and the same numeric value occurs more than once.

```
An item with the same key has already been added. Key: Pln
   at System.ThrowHelper.ThrowAddingDuplicateWithKeyArgumentException(Object key)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at Google.Protobuf.JsonFormatter.OriginalEnumValueHelper.GetNameMapping(Type enumType)
   at Google.Protobuf.JsonFormatter.OriginalEnumValueHelper.GetOriginalName(Object value)
   at Google.Protobuf.JsonFormatter.WriteValue(TextWriter writer, Object value)
   at Google.Protobuf.JsonFormatter.WriteMessageFields(TextWriter writer, IMessage message, Boolean assumeFirstFieldWritten)
   at Google.Protobuf.JsonFormatter.WriteMessage(TextWriter writer, IMessage message)
   at Google.Protobuf.JsonFormatter.WriteMessageFields(TextWriter writer, IMessage message, Boolean assumeFirstFieldWritten)
   at Google.Protobuf.JsonFormatter.WriteMessage(TextWriter writer, IMessage message)
   at Google.Protobuf.JsonFormatter.WriteList(TextWriter writer, IList list)
   at Google.Protobuf.JsonFormatter.WriteMessageFields(TextWriter writer, IMessage message, Boolean assumeFirstFieldWritten)
   at Google.Protobuf.JsonFormatter.WriteMessage(TextWriter writer, IMessage message)
   at Google.Protobuf.JsonFormatter.WriteList(TextWriter writer, IList list)
   at Google.Protobuf.JsonFormatter.WriteMessageFields(TextWriter writer, IMessage message, Boolean assumeFirstFieldWritten)
   at Google.Protobuf.JsonFormatter.WriteMessage(TextWriter writer, IMessage message)
   at Google.Protobuf.JsonFormatter.Format(IMessage message)
```

**Comment by dibyendumajumdar** [comment]
I can confirm that removing the allow_alias option and the duplicated enum values made the error go away, so it looks definitely related to that.

**Comment by jskeet** [comment]
@anandolee: There's a bit of design to be considered here - when there are several names for the same enum value, which one do we want to emit when formatting? Once that decision has been made, fixing the dictionary creation code should be simple. Apologies for not spotting this before...

**Comment by anandolee** [comment]
Did some small experimentals: C++ prints the first enum name, but python prints the last enum name.

There's no good solution yet but we should fix the exception at least. Talked with Jisi and we think use the first one might be better. Will fix
