### ISSUE TITLE
npm test fails due to missing proto.google.protobuf.Timestamp

### ISSUE THREAD

**Issue by seishun** [google/protobuf#2413]
Using current master:

```
~/protobuf/js$ node --version
v7.0.0
~/protobuf/js$ npm --version
3.10.9
~/protobuf/js$ npm test

> google-protobuf@3.1.0 test /home/drkoljan/protobuf/js
> node ./node_modules/gulp/bin/gulp.js test

[11:43:17] Using gulpfile ~/protobuf/js/gulpfile.js
[11:43:17] Starting 'genproto_closure'...
[11:43:17] Starting 'genproto_wellknowntypes'...
[11:43:17] Starting 'genproto_commonjs'...
[11:43:17] Starting 'genproto_commonjs_wellknowntypes'...
[11:43:17] Starting 'commonjs_asserts'...
[11:43:17] Starting 'commonjs_testdeps'...


[11:43:17] Finished 'genproto_commonjs_wellknowntypes' after 79 ms


[11:43:17] Finished 'genproto_wellknowntypes' after 87 ms
[11:43:17] Starting 'dist'...


[11:43:17] Finished 'genproto_commonjs' after 90 ms


[11:43:17] Finished 'genproto_closure' after 136 ms
[11:43:17] Starting 'deps'...


[11:43:17] Finished 'deps' after 144 ms
[11:43:17] Starting 'test_closure'...

goog.require could not find: proto.google.protobuf.Timestamp
/home/drkoljan/protobuf/js/node_modules/google-closure-library/closure/goog/base.js:673
    throw Error(errorMessage);
    ^

Error: goog.require could not find: proto.google.protobuf.Timestamp
    at Object.goog.require (/home/drkoljan/protobuf/js/node_modules/google-closure-library/closure/goog/base.js:673:11)
    at Object.<anonymous> (/home/drkoljan/protobuf/js/proto3_test.js:42:6)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
    at /home/drkoljan/protobuf/js/node_modules/jasmine/lib/jasmine.js:71:5

[11:43:18] 'test_closure' errored after 412 ms
[11:43:18] Error: Command failed: sh -c JASMINE_CONFIG_PATH=jasmine.json ./node_modules/.bin/jasmine
goog.require could not find: proto.google.protobuf.Timestamp
/home/drkoljan/protobuf/js/node_modules/google-closure-library/closure/goog/base.js:673
    throw Error(errorMessage);
    ^

Error: goog.require could not find: proto.google.protobuf.Timestamp
    at Object.goog.require (/home/drkoljan/protobuf/js/node_modules/google-closure-library/closure/goog/base.js:673:11)
    at Object.<anonymous> (/home/drkoljan/protobuf/js/proto3_test.js:42:6)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
    at /home/drkoljan/protobuf/js/node_modules/jasmine/lib/jasmine.js:71:5

    at ChildProcess.exithandler (child_process.js:211:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)

calcdeps.py: Scanning files...
calcdeps.py: Finding Closure dependencies...
calcdeps.py: Compiling with the following command: java -jar node_modules/google-closure-compiler/compiler.jar --js node_modules/google-closure-library/closure/goog/base.js --js node_modules/google-closure-library/closure/goog/testing/stacktrace.js --js node_modules/google-closure-library/closure/goog/testing/asserts.js --js commonjs/export_asserts.js

[11:43:31] Finished 'commonjs_asserts' after 14 s

calcdeps.py: Scanning files...
calcdeps.py: Finding Closure dependencies...
calcdeps.py: Compiling with the following command: java -jar node_modules/google-closure-compiler/compiler.jar --js node_modules/google-closure-library/closure/goog/base.js --js node_modules/google-closure-library/closure/goog/debug/error.js --js node_modules/google-closure-library/closure/goog/dom/nodetype.js --js node_modules/google-closure-library/closure/goog/string/string.js --js node_modules/google-closure-library/closure/goog/asserts/asserts.js --js node_modules/google-closure-library/closure/goog/array/array.js --js node_modules/google-closure-library/closure/goog/crypt/crypt.js --js node_modules/google-closure-library/closure/goog/labs/useragent/util.js --js node_modules/google-closure-library/closure/goog/object/object.js --js node_modules/google-closure-library/closure/goog/labs/useragent/browser.js --js node_modules/google-closure-library/closure/goog/labs/useragent/engine.js --js node_modules/google-closure-library/closure/goog/labs/useragent/platform.js --js node_modules/google-closure-library/closure/goog/useragent/useragent.js --js node_modules/google-closure-library/closure/goog/useragent/product.js --js node_modules/google-closure-library/closure/goog/crypt/base64.js --js node_modules/google-closure-library/closure/goog/json/json.js --js map.js --js message.js --js binary/constants.js --js binary/utils.js --js binary/decoder.js --js binary/reader.js --js binary/encoder.js --js binary/arith.js --js binary/writer.js --js commonjs/export.js

[11:43:31] Finished 'dist' after 14 s

calcdeps.py: Scanning files...
calcdeps.py: Finding Closure dependencies...
calcdeps.py: Compiling with the following command: java -jar node_modules/google-closure-compiler/compiler.jar --js node_modules/google-closure-library/closure/goog/base.js --js node_modules/google-closure-library/closure/goog/debug/error.js --js node_modules/google-closure-library/closure/goog/dom/nodetype.js --js node_modules/google-closure-library/closure/goog/string/string.js --js node_modules/google-closure-library/closure/goog/asserts/asserts.js --js node_modules/google-closure-library/closure/goog/array/array.js --js node_modules/google-closure-library/closure/goog/crypt/crypt.js --js node_modules/google-closure-library/closure/goog/labs/useragent/util.js --js node_modules/google-closure-library/closure/goog/object/object.js --js node_modules/google-closure-library/closure/goog/labs/useragent/browser.js --js node_modules/google-closure-library/closure/goog/labs/useragent/engine.js --js node_modules/google-closure-library/closure/goog/labs/useragent/platform.js --js node_modules/google-closure-library/closure/goog/useragent/useragent.js --js node_modules/google-closure-library/closure/goog/useragent/product.js --js node_modules/google-closure-library/closure/goog/crypt/base64.js --js binary/arith.js --js binary/constants.js --js binary/utils.js --js binary/encoder.js --js binary/decoder.js --js binary/writer.js --js commonjs/export_testdeps.js

[11:43:32] Finished 'commonjs_testdeps' after 14 s
npm ERR! Test failed.  See above for more details.
```

**Comment by seishun** [comment]
Never mind, I forgot to set `PROTOC`. I'm now getting "duplicate provide", but I'll submit a separate issue for that.
