### ISSUE TITLE
Cannot convert proto files to js format using pbjs

### ISSUE THREAD

**Issue by Arun-KumarH** [google/protobuf#2447]
I am trying to convert .proto file to javascript target but I am getting below error :
My protobufjs version is:
protobuf.js v6.0.2 cli

```
$ pbjs cat.proto -target=js > cat_pb.js
module.js:474
    throw err;
    ^
Error: Cannot find module '/restore/test/js'
    at Function.Module._resolveFilename (module.js:472:15)
    at Function.Module._load (module.js:420:25)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
    at Object.exports.main (/usr/lib64/node_modules/protobufjs/cli/pbjs.js:64:18)
    at Object.<anonymous> (/usr/lib64/node_modules/protobufjs/bin/pbjs:4:16)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
```

My proto file is below :
```
syntax = "proto3";

package demo;

message Cat {
   required string name = 1;
   required     int32 age = 2;

	message Parent {
		required     string name = 1;
	        required     string email = 2;
			}

	repeated Parent parents =4;
}
```
Cannot convert proto to js format using pbjs

**Comment by seishun** [comment]
You probably meant to post this in https://github.com/dcodeIO/protobuf.js
