### ISSUE TITLE
Test suite seg faults on OpenBSD

### ISSUE THREAD

**Issue by vext01** [google/protobuf#2452]
After applying the diff from #2419 to  the 3.1.0 sources, the test suitie now seg faults:

```
[ RUN      ] JsonUtilTest.TestParseErrors
[       OK ] JsonUtilTest.TestParseErrors (0 ms)
[ RUN      ] JsonUtilTest.TestDynamicMessage
[       OK ] JsonUtilTest.TestDynamicMessage (8 ms)
[----------] 7 tests from JsonUtilTest (10 ms total)

[----------] 1 test from ZeroCopyStreamByteSinkTest
[ RUN      ] ZeroCopyStreamByteSinkTest.TestAllInputOutputPatterns
[       OK ] ZeroCopyStreamByteSinkTest.TestAllInputOutputPatterns (120 ms)
[----------] 1 test from ZeroCopyStreamByteSinkTest (120 ms total)

[----------] 69 tests from JsonStreamParserTest
[ RUN      ] JsonStreamParserTest.SimpleTrue

Program received signal SIGSEGV, Segmentation fault.
0x000017d81787cd54 in testing::Sequence::AddExpectation () from ./src/.libs/libgmock.so.0.0
(gdb) bt
#0  0x000017d81787cd54 in testing::Sequence::AddExpectation () from ./src/.libs/libgmock.so.0.0
#1  0x000017d51b72cb02 in testing::internal::MockSpec<google::protobuf::util::converter::ObjectWriter* ()(google::protobuf::StringPiece, bool)>::InternalExpectedAt ()
   from /usr/local/pobj/protobuf-3.1.0/build-amd64/src/.libs/protobuf-test
#2  0x000017d51b72ceb5 in google::protobuf::util::converter::ExpectingObjectWriter::RenderBool ()
   from /usr/local/pobj/protobuf-3.1.0/build-amd64/src/.libs/protobuf-test
#3  0x000017d51b748b66 in google::protobuf::util::converter::JsonStreamParserTest_SimpleTrue_Test::TestBody () from /usr/local/pobj/protobuf-3.1.0/build-amd64/src/.libs/protobuf-test
#4  0x000017d777d7b2b1 in testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void> ()
   from ./src/.libs/libgtest.so.0.0
#5  0x000017d777d7198a in testing::Test::Run () from ./src/.libs/libgtest.so.0.0
#6  0x000017d73da26900 in ?? ()
#7  0x000017d7a1f5f400 in ?? ()
#8  0x000017d737dff6c0 in ?? ()
#9  0x000017d777d71ad8 in testing::TestInfo::Run () from ./src/.libs/libgtest.so.0.0
#10 0x000017d80688a198 in ?? ()
#11 0x0000000000000001 in ?? ()
#12 0x000017d74525c400 in ?? ()
#13 0x000017d7a1f5f400 in ?? ()
#14 0x000017d737dff6c0 in ?? ()
#15 0x000017d777d550e0 in testing::TestCase::total_test_count () from ./src/.libs/libgtest.so.0.0
#16 0x00000158d633626c in ?? ()
#17 0x000017d777d71bb5 in testing::TestCase::Run () from ./src/.libs/libgtest.so.0.0
#18 0x000017d777d71ec8 in testing::internal::UnitTestImpl::RunAllTests ()
   from ./src/.libs/libgtest.so.0.0
#19 0x00000779c072a34e in ?? ()
#20 0x0000000100000000 in ?? ()
#21 0x000017d792d04873 in _dl_bind (object=0x0, index=Variable "index" is not available.
)
    at /usr/src/libexec/ld.so/amd64/rtld_machine.c:363
#22 0x000017d777e98c88 in testing::internal::kStackTraceMarker () from ./src/.libs/libgtest.so.0.0
#23 0x0000000000000000 in ?? ()
```

Sorry about the lack of symbols. I'll try to get some in and post a new trace.

This was with gcc-4.9.3 and gtest-1.8.0.

**Comment by xfxyjwf** [comment]
Could you try the master version instead?

**Comment by vext01** [comment]
Seems master does not build:

```
...
libtool: compile:  eg++ -DHAVE_CONFIG_H -I. -I.. -pthread -DHAVE_PTHREAD=1 -DHAVE_ZLIB=1 -Wall -Wno-sign-compare -O2 -pipe -g -MT google/protobuf/compiler/code_generator.lo -MD -MP -MF google/protobuf/compiler/.deps/code_generator.Tpo -c google/protobuf/compiler/code_generator.cc  -fPIC -DPIC -o google/protobuf/compiler/.libs/code_generator.o
In file included from /usr/include/stdio.h:46:0,
                 from /usr/include/wchar.h:66,
                 from /usr/local/include/c++/4.9.4/cwchar:44,
                 from /usr/local/include/c++/4.9.4/bits/postypes.h:40,
                 from /usr/local/include/c++/4.9.4/bits/char_traits.h:40,
                 from /usr/local/include/c++/4.9.4/string:40,
                 from ./google/protobuf/stubs/common.h:38,
                 from ./google/protobuf/compiler/code_generator.h:41,
                 from google/protobuf/compiler/code_generator.cc:35:
./google/protobuf/compiler/plugin.pb.h:214:29: error: expected identifier before '(' token
   ::google::protobuf::int32 major() const;
                             ^
./google/protobuf/compiler/plugin.pb.h:214:29: error: expected ')' before '>>' token
   ::google::protobuf::int32 major() const;
                             ^
./google/protobuf/compiler/plugin.pb.h:214:29: error: expected ')' before '>>' token
./google/protobuf/compiler/plugin.pb.h:214:29: error: expected ')' before '>>' token
./google/protobuf/compiler/plugin.pb.h:221:29: error: expected identifier before '(' token
   ::google::protobuf::int32 minor() const;
                             ^
./google/protobuf/compiler/plugin.pb.h:221:29: error: expected ',' or '...' before '&' token
   ::google::protobuf::int32 minor() const;
                             ^
./google/protobuf/compiler/plugin.pb.h:221:29: error: expected ')' before '|' token
   ::google::protobuf::int32 minor() const;
                             ^
./google/protobuf/compiler/plugin.pb.h:685:43: error: expected unqualified-id before '(' token
 inline ::google::protobuf::int32 Version::major() const {
                                           ^
./google/protobuf/compiler/plugin.pb.h:709:43: error: expected unqualified-id before '(' token
 inline ::google::protobuf::int32 Version::minor() const {
```
