### ISSUE TITLE
C# protobuf fails on large messages

### ISSUE THREAD

**Issue by bootstraponline** [google/protobuf#2540]
When I receive a large message, the C# protobuf implementation is failing. If I reduce the amount of data being sent, then protobuf doesn't throw an exception.

Is there a configuration setting to increase the upper range?

```
W1225 21:45:14.803317 Grpc.Core.Internal.UnaryServerCallHandler`2 Exception occured in handler. System.ArgumentException: Value does not fall within the expected range.
   at Grpc.Core.Internal.UnaryServerCallHandler`2.<HandleCall>d__0.MoveNext()
W1225 21:45:14.811416 Grpc.Core.Server Exception while handling RPC. System.InvalidOperationException: Error sending status from server.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Grpc.Core.Internal.UnaryServerCallHandler`2.<HandleCall>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Grpc.Core.Server.<HandleCallAsync>d__11.MoveNext()
```

**Comment by bootstraponline** [comment]
Looks like this should be on the grpc repo, not protobuf. Moving.
