### ISSUE TITLE
Timestamp to json error 

### ISSUE THREAD

**Issue by luistrigueiros** [google/protobuf#2593]
Hi,

I am getting an error while rendering a protobuf message object with timestamp object to json.
But it works fine in the toString method. There a value validation for the seconds that looks to be wrong because is using hardcored values. I have created a test case to reproduce the error:

`

import com.google.protobuf.InvalidProtocolBufferException;
import com.google.protobuf.Timestamp;
import com.google.protobuf.util.JsonFormat;
import org.junit.Test;

import java.time.Instant;

public class Timestamptest {
    @Test
    public void testTimestampToJson() throws InvalidProtocolBufferException {
        long now = Instant.now().toEpochMilli();
        Timestamp timestamp = Timestamp.newBuilder().setSeconds( now).build();
        System.out.println( JsonFormat.printer().print(timestamp));
    }

}

`

The error  is:

java.lang.IllegalArgumentException: Timestamp is not valid. See proto definition for valid values. Seconds (1484428772754) must be in range [-62,135,596,800, +253,402,300,799]. Nanos (0) must be in range [0, +999,999,999].

	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:145)
	at com.google.protobuf.util.Timestamps.checkValid(Timestamps.java:155)
	at com.google.protobuf.util.Timestamps.toString(Timestamps.java:177)
	at com.google.protobuf.util.JsonFormat$PrinterImpl.printTimestamp(JsonFormat.java:708)
	at com.google.protobuf.util.JsonFormat$PrinterImpl.access$1100(JsonFormat.java:503)
	at com.google.protobuf.util.JsonFormat$PrinterImpl$3.print(JsonFormat.java:590)
	at com.google.protobuf.util.JsonFormat$PrinterImpl.print(JsonFormat.java:543)
	at com.google.protobuf.util.JsonFormat$Printer.appendTo(JsonFormat.java:202)
	at com.google.protobuf.util.JsonFormat$Printer.print(JsonFormat.java:212)
	at com.cartrawler.integration.Timestamptest.testTimestampToJson(Timestamptest.java:15)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:117)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:42)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:262)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:84)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)

**Comment by xfxyjwf** [comment]
I believe you are mistakenly putting "now" represented as milliseconds into setSeconds() and it's indeed out of range.

**Comment by luistrigueiros** [comment]
Hi @xfxyjwf :+1:
When will this be avaiable as a fix ?
Thank you. Oscar

**Comment by xfxyjwf** [comment]
@luistrigueiros I was suggesting your test is incorrect. There is nothing to be fixed in protobuf here.
