### ISSUE TITLE
[python] Unpegged requirement on `setuptools` causing build failures

### ISSUE THREAD

**Issue by tehranian** [google/protobuf#2628]
See https://github.com/google/protobuf/blob/0aa5af3e68940325a1c4ef9a8cacb3d072ba4baa/python/setup.py#L216

There was a new release of `setuptools` last night, and our builds suddenly started breaking because of the unpegged requirement of `setuptools` in this `protopuf` library:

```
Downloading/unpacking setuptools from https://pypi.dev.twilio.com/packages/source/s/setuptools/setuptools-34.0.2.zip (from protobuf==3.0.0->starship==2.11.9)
  Running setup.py egg_info for package setuptools
    Traceback (most recent call last):
      File "<string>", line 3, in <module>
      File "setuptools/__init__.py", line 10, in <module>
        from six.moves import filter, map
    ImportError: No module named six.moves
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 3, in <module>

  File "setuptools/__init__.py", line 10, in <module>

    from six.moves import filter, map

ImportError: No module named six.moves
```

**Comment by pherl** [comment]
It requires a more updated version of six. I will close this now and let me know if there is still an issue.
