### ISSUE TITLE
`TypeError: __init__() got an unexpected keyword argument 'syntax'` for address book python example on MacOS

### ISSUE THREAD

**Issue by kristovatlas** [google/protobuf#2779]
```
$ make python
protoc --cpp_out=. --java_out=. --python_out=. addressbook.proto
Writing shortcut script add_person_python...
Writing shortcut script list_people_python...
```

```
$ ls
AddPerson.java		README.txt		add_person_python	addressbook.proto	list_people.go		protoc_middleman
CMakeLists.txt		add_person.cc		add_person_test.go	addressbook_pb2.py	list_people.py
ListPeople.java		add_person.go		addressbook.pb.cc	com			list_people_python
Makefile		add_person.py		addressbook.pb.h	list_people.cc		list_people_test.go
```

```
$ python add_person.py 
Traceback (most recent call last):
  File "add_person.py", line 5, in <module>
    import addressbook_pb2
  File "/Users/myusername/Downloads/protobuf-master/examples/addressbook_pb2.py", line 22, in <module>
    serialized_pb=_b('\n\x11\x61\x64\x64ressbook.proto\x12\x08tutorial\"\xd5\x01\n\x06Person\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\n\n\x02id\x18\x02 \x01(\x05\x12\r\n\x05\x65mail\x18\x03 \x01(\t\x12,\n\x06phones\x18\x04 \x03(\x0b\x32\x1c.tutorial.Person.PhoneNumber\x1aG\n\x0bPhoneNumber\x12\x0e\n\x06number\x18\x01 \x01(\t\x12(\n\x04type\x18\x02 \x01(\x0e\x32\x1a.tutorial.Person.PhoneType\"+\n\tPhoneType\x12\n\n\x06MOBILE\x10\x00\x12\x08\n\x04HOME\x10\x01\x12\x08\n\x04WORK\x10\x02\"/\n\x0b\x41\x64\x64ressBook\x12 \n\x06people\x18\x01 \x03(\x0b\x32\x10.tutorial.PersonBP\n\x14\x63om.example.tutorialB\x11\x41\x64\x64ressBookProtos\xaa\x02$Google.Protobuf.Examples.AddressBookb\x06proto3')
TypeError: __init__() got an unexpected keyword argument 'syntax'
```

```
$ python --version
Python 2.7.13
```

The `TypeError: __init__() got an unexpected keyword argument 'syntax'` error is also referenced in this issue: https://github.com/google/protobuf/issues/1491

I've tried this with protoc versions 3.2.0 and 3.1.0 installed via Homebrew.

**Comment by kristovatlas** [comment]
Hi @anandolee, please let me know if there are additional details I can provide to clarify the issue.

**Comment by anandolee** [comment]
Have you installed the corresponding  python protobuf runtime? Looks like it is an old runtime that does not recognize 'syntax'

**Comment by kristovatlas** [comment]
By "python protobuf runtime," do you mean the python module for protobuf?

```
$ python
Python 2.7.13 (default, Jan 20 2017, 18:54:19) 
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import google.protobuf
>>> google.protobuf
<module 'google.protobuf' from '/usr/local/lib/python2.7/site-packages/protobuf-3.2.0-py2.7.egg/google/protobuf/__init__.pyc'>
>>> dir(google.protobuf)
['__builtins__', '__doc__', '__file__', '__name__', '__package__', '__path__', '__version__']
>>> google.protobuf.__version__
'3.2.0'
```

**Comment by anandolee** [comment]
I can't think out other reasons except the version mismatch. Can you try uninstall the both protoc and protobuf runtime, then reinstall again? 

This issue looks similar with yours:
https://github.com/BVLC/caffe/issues/2092

**Comment by anandolee** [comment]
Closing it for clean up. Feel free to reopen if needed
