### ISSUE TITLE
Text Format Splits Lines on \n even if quoted

### ISSUE THREAD

**Issue by aidan-plenert-macdonald** [google/protobuf#2798]
I believe I found a bug with the text_format calls where it will split the messages on \n but doesn't take into account surrounding quotes (ie. "\n" shouldn't get split to ['"\n', '"'])

As a background, I am trying to get Tensorflow to expose the documentation in Python. http://stackoverflow.com/questions/42521166/tensorflow-operation-documentation

Which lead me to attempt commenting out the line https://github.com/tensorflow/tensorflow/blob/a3e636c0f561e2ac6d9f8a0044fbe09acb003803/tensorflow/python/framework/python_op_gen.cc#L708 which removes documentation (as far as I am aware)

After building, I tried testing and got the error,
```
~$ python -c "from tensorflow.python.ops import gen_array_ops; print gen_array_ops._InitOpDefLibrary()._ops['BroadcastGradientArgs'].op_def"

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/__init__.py", line 84, in <module>
    from tensorflow.python.framework.framework_lib import *
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/framework_lib.py", line 98, in <module>
    from tensorflow.python.framework.subscribe import subscribe
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/subscribe.py", line 25, in <module>
    from tensorflow.python.ops import array_ops
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/array_ops.py", line 114, in <module>
    from tensorflow.python.ops import gen_array_ops
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_array_ops.py", line 7193, in <module>
    _op_def_lib = _InitOpDefLibrary()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_array_ops.py", line 4039, in _InitOpDefLibrary
    _text_format.Merge(_InitOpDefLibrary.op_list_ascii, op_list)
  File "/usr/local/lib/python2.7/dist-packages/google/protobuf/text_format.py", line 477, in Merge
    descriptor_pool=descriptor_pool)
  File "/usr/local/lib/python2.7/dist-packages/google/protobuf/text_format.py", line 527, in MergeLines
    return parser.MergeLines(lines, message)
  File "/usr/local/lib/python2.7/dist-packages/google/protobuf/text_format.py", line 560, in MergeLines
    self._ParseOrMerge(lines, message)
  File "/usr/local/lib/python2.7/dist-packages/google/protobuf/text_format.py", line 575, in _ParseOrMerge
    self._MergeField(tokenizer, message)
  File "/usr/local/lib/python2.7/dist-packages/google/protobuf/text_format.py", line 676, in _MergeField
    merger(tokenizer, message, field)
  File "/usr/local/lib/python2.7/dist-packages/google/protobuf/text_format.py", line 765, in _MergeMessageField
    self._MergeField(tokenizer, sub_message)
  File "/usr/local/lib/python2.7/dist-packages/google/protobuf/text_format.py", line 676, in _MergeField
    merger(tokenizer, message, field)
  File "/usr/local/lib/python2.7/dist-packages/google/protobuf/text_format.py", line 765, in _MergeMessageField
    self._MergeField(tokenizer, sub_message)
  File "/usr/local/lib/python2.7/dist-packages/google/protobuf/text_format.py", line 676, in _MergeField
    merger(tokenizer, message, field)
  File "/usr/local/lib/python2.7/dist-packages/google/protobuf/text_format.py", line 810, in _MergeScalarField
    value = tokenizer.ConsumeString()
  File "/usr/local/lib/python2.7/dist-packages/google/protobuf/text_format.py", line 1152, in ConsumeString
    the_bytes = self.ConsumeByteString()
  File "/usr/local/lib/python2.7/dist-packages/google/protobuf/text_format.py", line 1167, in ConsumeByteString
    the_list = [self._ConsumeSingleByteString()]
  File "/usr/local/lib/python2.7/dist-packages/google/protobuf/text_format.py", line 1189, in _ConsumeSingleByteString
    raise self.ParseError('String missing ending quote: %r' % (text,))
google.protobuf.text_format.ParseError: 93:18 : String missing ending quote: '"4-D tensor with shape'
```

Note that the offending line comes from,
```
tensorflow$ grep "4-D tensor with shape" `find ./ -type f`
./tensorflow/core/ops/array_ops.cc:input: 4-D tensor with shape
./tensorflow/core/ops/ops.pbtxt:    description: "4-D tensor with shape\n`[batch*block_size*block_size, height_pad/block_size, width_pad/block_size,\n  depth]`. Note that the batch size of the input tensor must be divisible by\n`block_size * block_size`."
./tensorflow/go/op/wrappers.go://	input: 4-D tensor with shape
./tensorflow/g3doc/api_docs/python/functions_and_classes/shard1/tf.batch_to_space.md:*  <b>`input`</b>: A `Tensor`. 4-D tensor with shape
./tensorflow/g3doc/api_docs/python/array_ops.md:*  <b>`input`</b>: A `Tensor`. 4-D tensor with shape
```
where we see an annoying little \n after the word shape.

After tracing the error back, I found that the line https://github.com/google/protobuf/blob/master/python/google/protobuf/text_format.py#L472
appears to cause the splitting that I don't want by doing a simple split on \n rather than taking into account potential newlines existing withing quotes.

I was able to partially solve this with Regex,
```
  lines = re.findall('(?:[^\"\n]|(?:\"(?:[^\"]|[\n])*\"))*\n?', text)
  assert text == "".join(lines)
  for line in lines:
      assert line.count('"') % 2 ==	0

  return MergeLines(
      lines,
      message,
      allow_unknown_extension,
      allow_field_number,
      descriptor_pool=descriptor_pool)
```

this led to another error,
```
  File "/usr/local/lib/python2.7/dist-packages/google/protobuf/text_format.py", line 1167, in ConsumeByteString
    the_list = [self._ConsumeSingleByteString()]
  File "/usr/local/lib/python2.7/dist-packages/google/protobuf/text_format.py", line 1186, in _ConsumeSingleByteString
    raise self.ParseError('Expected string but found: %r' % (text,))
google.protobuf.text_format.ParseError: 3:1 : Expected string but found: 'BatchMatrixBandPart'
```
~~because the regex might be stripping the quotes off. I have yet to investigate this.~~
~~Regex is bad. Working on it~~

Fixed regex above. There was another problem in an existing Regex statement. The _TOKEN regex wasn't accepting "aaa\naaa" style strings.

```
938c939
<       r'{qt}([^{qt}\n\\]|\\.)*({qt}|\\?$)'.format(qt=mark) for mark in _QUOTES
---
>       r'{qt}([^{qt}\\]|\\.)*({qt}|\\?$)'.format(qt=mark) for mark in _QUOTES
```

Latest error,
```
  File "/usr/local/lib/python2.7/dist-packages/google/protobuf/text_format.py", line 770, in _MergeMessageField
    self._MergeField(tokenizer, sub_message)
  File "/usr/local/lib/python2.7/dist-packages/google/protobuf/text_format.py", line 649, in _MergeField
    (message_descriptor.full_name, name))
google.protobuf.text_format.ParseError: 184:46 : Message type "tensorflow.OpDef" has no field named "batch".
```

Last error was caused by TF https://github.com/tensorflow/tensorflow/issues/8207

# Solution

Just 2 regex statements! But let me be the first to admit how painful those were to write!

```
472c473
<       text.split('\n'),
---
>       re.findall('(?:[^\"\n]|(?:\"(?:[^\"]|[\n])*\"))*\n?', text),
938c939
<       r'{qt}([^{qt}\n\\]|\\.)*({qt}|\\?$)'.format(qt=mark) for mark in _QUOTES
---
>       r'{qt}([^{qt}\\]|\\.)*({qt}|\\?$)'.format(qt=mark) for mark in _QUOTES
```

**Comment by anandolee** [comment]
Please try "\\n" instead?  The text format output also print "\\n" for "\n"

**Comment by aidan-plenert-macdonald** [comment]
@anandolee `'\\n'` isn't a newline character. I had a solution above. Your proposal doesn't address the problem. The problem was `'\n'`'s enclosed in quotes. Did you look at the Regex above?
