### ISSUE TITLE
protojson: not deserializable: Java "oneof" fields always prints raw enums (and other default values) with includingDefaultValueFields

### ISSUE THREAD

**Issue by Xorlev** [google/protobuf#2865]
To set the stage, I have a proto3 proto that roughly looks like the following:

```proto
syntax proto3;

enum MyEnum {
    DEFAULT = 0;
    ONE = 1;
}

message UnionType {
    oneof union {
        MyEnum enum = 1;
        string something_else = 2;
    }
}

message Response {
    repeated UnionType things = 1;
}
```

And some code to reproduce the issue:

```java
JsonFormat.Printer printer = JsonFormat.printer().includingDefaultValueFields();

Response response = Response.newBuilder()
                            .addThings(UnionType.newBuilder().setSomethingElse("test"))
                            .addThings(UnionType.newBuilder().setSomethingElse("test2"))
                            .addThings(UnionType.newBuilder().setEnum(MyEnum.ONE))
                            .build();

String json = printer.print(response);
System.out.println(json);

Response.Builder deserialized = Response.newBuilder();
JsonFormat.parser().merge(json, deserialized); // InvalidProtocolBufferException
assertEquals(response, deserialized.build());
```

I expect that the JSON should look like the following:

```json
{
  "things": [{
    "somethingElse": "test"
  }, {
    "somethingElse": "test2"
  }, {
    "enum": "ONE"
  }]
}
```

But is actually

```json
{
  "things": [{
    "enum": "DEFAULT",
    "somethingElse": "test"
  }, {
    "enum": "DEFAULT",
    "somethingElse": "test2"
  }, {
    "enum": "ONE",
    "somethingElse": ""
  }]
}
```

The problem being that attempting to deserialize the above leads to failure upon deserialization:

```
com.google.protobuf.InvalidProtocolBufferException: Cannot set field UnionType.something_else because another field UnionType.enum belonging to the same oneof has already been set 

	at com.google.protobuf.util.JsonFormat$ParserImpl.mergeField(JsonFormat.java:1374)
	at com.google.protobuf.util.JsonFormat$ParserImpl.mergeMessage(JsonFormat.java:1220)
	at com.google.protobuf.util.JsonFormat$ParserImpl.merge(JsonFormat.java:1178)
```

I'd expect a oneof to _not_ print any other field's default values since only one can be set.

If there isn't already a fix somewhere for this, I'll submit a PR referencing this issue.

**Comment by xfxyjwf** [comment]
What version are you using? The issue was already fixed by this commit:
https://github.com/google/protobuf/commit/1a56251a3582d8b060ca65db6ef1d178c744f81f

Supposedly it has made into v3.2.0 so if you upgrade to v3.2.0 the problem should go away.

**Comment by Xorlev** [comment]
I'm on 3.1.0, will upgrade. Thanks!

**Comment by xfxyjwf** [comment]
BTW, thanks for the detailed bug report! :)

**Comment by BenNeighbour** [comment]
Hi all, I am having the same problem however I am on a newer version, my gradle dependency is as follows: 

```
compile group: 'com.google.protobuf', name: 'protobuf-java-util', version: '4.0.0-rc-2'
```

any updates or help would be much appreciated! 
Thanks
