### ISSUE TITLE
Pylint segfault while trying to check generated file

### ISSUE THREAD

**Issue by i-feofilaktov** [google/protobuf#2911]
Versions:
Protobuf:
```
$ sudo pip freeze | grep proto
protobuf==3.2.0
```
Protoc:
```
$ sudo /usr/local/bin/protoc --version
libprotoc 3.1.0
```
Pylint
```
$ sudo pip freeze | grep pylint
pylint==1.6.5
```
Trying to check generated file from helloworld grpc example: https://github.com/grpc/grpc/blob/master/examples/python/helloworld/helloworld_pb2.py
Here's gdb backtrace:
```
$ gdb python /tmp/cores/core.pylint.1763.centos-runtime.1490694728
GNU gdb (GDB) Red Hat Enterprise Linux 7.6.1-94.el7
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
Reading symbols from /usr/bin/python3.4...Reading symbols from /usr/bin/python3.4...(no debugging symbols found)...done.
(no debugging symbols found)...done.

warning: core file may not match specified executable file.
[New LWP 1763]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by `/usr/bin/python3.4 /usr/bin/pylint examples/python/helloworld/helloworld_pb2.py'.
Program terminated with signal 11, Segmentation fault.
#0  google::protobuf::python::message_meta::GetExtensionsByName (self=0x7fc525783ea0 <google::protobuf::python::CMessage_Type>, closure=<optimized out>) at google/protobuf/pyext/message.cc:351
351	google/protobuf/pyext/message.cc: No such file or directory.
Missing separate debuginfos, use: debuginfo-install bzip2-libs-1.0.6-13.el7.x86_64 expat-2.1.0-10.el7_3.x86_64 glibc-2.17-157.el7_3.1.x86_64 keyutils-libs-1.5.8-3.el7.x86_64 krb5-libs-1.14.1-27.el7_3.x86_64 libcom_err-1.42.9-9.el7.x86_64 libgcc-4.8.5-11.el7.x86_64 libselinux-2.5-6.el7.x86_64 libstdc++-4.8.5-11.el7.x86_64 openssl-libs-1.0.1e-60.el7_3.1.x86_64 pcre-8.32-15.el7_2.1.x86_64 python34-3.4.5-3.el7.x86_64 python34-libs-3.4.5-3.el7.x86_64 xz-libs-5.2.2-1.el7.x86_64 zlib-1.2.7-17.el7.x86_64
(gdb) bt
#0  google::protobuf::python::message_meta::GetExtensionsByName (self=0x7fc525783ea0 <google::protobuf::python::CMessage_Type>, closure=<optimized out>) at google/protobuf/pyext/message.cc:351
#1  0x00007fc52c4b7d7e in getset_get () from /lib64/libpython3.4m.so.1.0
#2  0x00007fc52c54970b in builtin_getattr () from /lib64/libpython3.4m.so.1.0
#3  0x00007fc52c555782 in PyEval_EvalFrameEx () from /lib64/libpython3.4m.so.1.0
#4  0x00007fc52c555450 in PyEval_EvalFrameEx () from /lib64/libpython3.4m.so.1.0
#5  0x00007fc52c555450 in PyEval_EvalFrameEx () from /lib64/libpython3.4m.so.1.0
#6  0x00007fc52c55654e in PyEval_EvalCodeEx () from /lib64/libpython3.4m.so.1.0
#7  0x00007fc52c554022 in PyEval_EvalFrameEx () from /lib64/libpython3.4m.so.1.0
#8  0x00007fc52c55654e in PyEval_EvalCodeEx () from /lib64/libpython3.4m.so.1.0
#9  0x00007fc52c554022 in PyEval_EvalFrameEx () from /lib64/libpython3.4m.so.1.0
#10 0x00007fc52c55654e in PyEval_EvalCodeEx () from /lib64/libpython3.4m.so.1.0
#11 0x00007fc52c554022 in PyEval_EvalFrameEx () from /lib64/libpython3.4m.so.1.0
#12 0x00007fc52c55654e in PyEval_EvalCodeEx () from /lib64/libpython3.4m.so.1.0
#13 0x00007fc52c554022 in PyEval_EvalFrameEx () from /lib64/libpython3.4m.so.1.0
#14 0x00007fc52c55654e in PyEval_EvalCodeEx () from /lib64/libpython3.4m.so.1.0
#15 0x00007fc52c554022 in PyEval_EvalFrameEx () from /lib64/libpython3.4m.so.1.0
#16 0x00007fc52c55654e in PyEval_EvalCodeEx () from /lib64/libpython3.4m.so.1.0
#17 0x00007fc52c4c66a3 in function_call () from /lib64/libpython3.4m.so.1.0
#18 0x00007fc52c49ddcc in PyObject_Call () from /lib64/libpython3.4m.so.1.0
#19 0x00007fc52c551dd9 in PyEval_EvalFrameEx () from /lib64/libpython3.4m.so.1.0
#20 0x00007fc52c55654e in PyEval_EvalCodeEx () from /lib64/libpython3.4m.so.1.0
#21 0x00007fc52c4c65ae in function_call () from /lib64/libpython3.4m.so.1.0
#22 0x00007fc52c49ddcc in PyObject_Call () from /lib64/libpython3.4m.so.1.0
#23 0x00007fc52c49ea1c in PyObject_CallFunctionObjArgs () from /lib64/libpython3.4m.so.1.0
#24 0x00007fc52a94c087 in WraptBoundFunctionWrapper_call (self=0x7fc525f6a180, args=<optimized out>, kwds=0x7fc525bfb208) at src/wrapt/_wrappers.c:2400
#25 0x00007fc52c49ddcc in PyObject_Call () from /lib64/libpython3.4m.so.1.0
#26 0x00007fc52c550f12 in PyEval_EvalFrameEx () from /lib64/libpython3.4m.so.1.0
#27 0x00007fc52c55654e in PyEval_EvalCodeEx () from /lib64/libpython3.4m.so.1.0
#28 0x00007fc52c4c66a3 in function_call () from /lib64/libpython3.4m.so.1.0
#29 0x00007fc52c49ddcc in PyObject_Call () from /lib64/libpython3.4m.so.1.0
#30 0x00007fc52c551dd9 in PyEval_EvalFrameEx () from /lib64/libpython3.4m.so.1.0
#31 0x00007fc52c4bf8ff in gen_send_ex.isra.1 () from /lib64/libpython3.4m.so.1.0
#32 0x00007fc52c5500a4 in PyEval_EvalFrameEx () from /lib64/libpython3.4m.so.1.0
#33 0x00007fc52c4bf8ff in gen_send_ex.isra.1 () from /lib64/libpython3.4m.so.1.0
#34 0x00007fc52c5500a4 in PyEval_EvalFrameEx () from /lib64/libpython3.4m.so.1.0
#35 0x00007fc52c4bf8ff in gen_send_ex.isra.1 () from /lib64/libpython3.4m.so.1.0
#36 0x00007fc52c5500a4 in PyEval_EvalFrameEx () from /lib64/libpython3.4m.so.1.0
#37 0x00007fc52c4bf8ff in gen_send_ex.isra.1 () from /lib64/libpython3.4m.so.1.0
#38 0x00007fc52c5500a4 in PyEval_EvalFrameEx () from /lib64/libpython3.4m.so.1.0
#39 0x00007fc52c4bf8ff in gen_send_ex.isra.1 () from /lib64/libpython3.4m.so.1.0
#40 0x00007fc52c5500a4 in PyEval_EvalFrameEx () from /lib64/libpython3.4m.so.1.0
#41 0x00007fc52c4bf8ff in gen_send_ex.isra.1 () from /lib64/libpython3.4m.so.1.0
#42 0x00007fc52c5500a4 in PyEval_EvalFrameEx () from /lib64/libpython3.4m.so.1.0
#43 0x00007fc52c4bf8ff in gen_send_ex.isra.1 () from /lib64/libpython3.4m.so.1.0
#44 0x00007fc52c5500a4 in PyEval_EvalFrameEx () from /lib64/libpython3.4m.so.1.0
#45 0x00007fc52c4bf8ff in gen_send_ex.isra.1 () from /lib64/libpython3.4m.so.1.0
#46 0x00007fc52c5500a4 in PyEval_EvalFrameEx () from /lib64/libpython3.4m.so.1.0
#47 0x00007fc52c4bf8ff in gen_send_ex.isra.1 () from /lib64/libpython3.4m.so.1.0
#48 0x00007fc52c5500a4 in PyEval_EvalFrameEx () from /lib64/libpython3.4m.so.1.0
#49 0x00007fc52c4bf8ff in gen_send_ex.isra.1 () from /lib64/libpython3.4m.so.1.0
#50 0x00007fc52c5500a4 in PyEval_EvalFrameEx () from /lib64/libpython3.4m.so.1.0
#51 0x00007fc52c55654e in PyEval_EvalCodeEx () from /lib64/libpython3.4m.so.1.0
#52 0x00007fc52c554022 in PyEval_EvalFrameEx () from /lib64/libpython3.4m.so.1.0
#53 0x00007fc52c4bf8ff in gen_send_ex.isra.1 () from /lib64/libpython3.4m.so.1.0
#54 0x00007fc52c5500a4 in PyEval_EvalFrameEx () from /lib64/libpython3.4m.so.1.0
#55 0x00007fc52c4bf8ff in gen_send_ex.isra.1 () from /lib64/libpython3.4m.so.1.0
#56 0x00007fc52c5500a4 in PyEval_EvalFrameEx () from /lib64/libpython3.4m.so.1.0
#57 0x00007fc52c4bf8ff in gen_send_ex.isra.1 () from /lib64/libpython3.4m.so.1.0
#58 0x00007fc52c5500a4 in PyEval_EvalFrameEx () from /lib64/libpython3.4m.so.1.0
#59 0x00007fc52c4bf8ff in gen_send_ex.isra.1 () from /lib64/libpython3.4m.so.1.0
#60 0x00007fc52c5500a4 in PyEval_EvalFrameEx () from /lib64/libpython3.4m.so.1.0
#61 0x00007fc52c4bf8ff in gen_send_ex.isra.1 () from /lib64/libpython3.4m.so.1.0
#62 0x00007fc52c5500a4 in PyEval_EvalFrameEx () from /lib64/libpython3.4m.so.1.0
---Type <return> to continue, or q <return> to quit---
#63 0x00007fc52c4bf8ff in gen_send_ex.isra.1 () from /lib64/libpython3.4m.so.1.0
#64 0x00007fc52c5500a4 in PyEval_EvalFrameEx () from /lib64/libpython3.4m.so.1.0
#65 0x00007fc52c4bf8ff in gen_send_ex.isra.1 () from /lib64/libpython3.4m.so.1.0
#66 0x00007fc52c5500a4 in PyEval_EvalFrameEx () from /lib64/libpython3.4m.so.1.0
#67 0x00007fc52c4bf8ff in gen_send_ex.isra.1 () from /lib64/libpython3.4m.so.1.0
#68 0x00007fc52c5500a4 in PyEval_EvalFrameEx () from /lib64/libpython3.4m.so.1.0
#69 0x00007fc52c4bf8ff in gen_send_ex.isra.1 () from /lib64/libpython3.4m.so.1.0
#70 0x00007fc52c5500a4 in PyEval_EvalFrameEx () from /lib64/libpython3.4m.so.1.0
#71 0x00007fc52c4bf8ff in gen_send_ex.isra.1 () from /lib64/libpython3.4m.so.1.0
#72 0x00007fc52c5500a4 in PyEval_EvalFrameEx () from /lib64/libpython3.4m.so.1.0
#73 0x00007fc52c4bf8ff in gen_send_ex.isra.1 () from /lib64/libpython3.4m.so.1.0
#74 0x00007fc52c5500a4 in PyEval_EvalFrameEx () from /lib64/libpython3.4m.so.1.0
#75 0x00007fc52c4bf8ff in gen_send_ex.isra.1 () from /lib64/libpython3.4m.so.1.0
#76 0x00007fc52c5500a4 in PyEval_EvalFrameEx () from /lib64/libpython3.4m.so.1.0
#77 0x00007fc52c4bf8ff in gen_send_ex.isra.1 () from /lib64/libpython3.4m.so.1.0
#78 0x00007fc52c5500a4 in PyEval_EvalFrameEx () from /lib64/libpython3.4m.so.1.0
#79 0x00007fc52c4bf8ff in gen_send_ex.isra.1 () from /lib64/libpython3.4m.so.1.0
#80 0x00007fc52c5500a4 in PyEval_EvalFrameEx () from /lib64/libpython3.4m.so.1.0
#81 0x00007fc52c4bf8ff in gen_send_ex.isra.1 () from /lib64/libpython3.4m.so.1.0
#82 0x00007fc52c5500a4 in PyEval_EvalFrameEx () from /lib64/libpython3.4m.so.1.0
#83 0x00007fc52c4bf8ff in gen_send_ex.isra.1 () from /lib64/libpython3.4m.so.1.0
#84 0x00007fc52c5500a4 in PyEval_EvalFrameEx () from /lib64/libpython3.4m.so.1.0
#85 0x00007fc52c4bf8ff in gen_send_ex.isra.1 () from /lib64/libpython3.4m.so.1.0
#86 0x00007fc52c5500a4 in PyEval_EvalFrameEx () from /lib64/libpython3.4m.so.1.0
#87 0x00007fc52c4bf8ff in gen_send_ex.isra.1 () from /lib64/libpython3.4m.so.1.0
#88 0x00007fc52c5500a4 in PyEval_EvalFrameEx () from /lib64/libpython3.4m.so.1.0
#89 0x00007fc52c4bf8ff in gen_send_ex.isra.1 () from /lib64/libpython3.4m.so.1.0
#90 0x00007fc52c5500a4 in PyEval_EvalFrameEx () from /lib64/libpython3.4m.so.1.0
#91 0x00007fc52c4bf8ff in gen_send_ex.isra.1 () from /lib64/libpython3.4m.so.1.0
#92 0x00007fc52c5500a4 in PyEval_EvalFrameEx () from /lib64/libpython3.4m.so.1.0
#93 0x00007fc52c4bf8ff in gen_send_ex.isra.1 () from /lib64/libpython3.4m.so.1.0
#94 0x00007fc52c5500a4 in PyEval_EvalFrameEx () from /lib64/libpython3.4m.so.1.0
#95 0x00007fc52c4bf8ff in gen_send_ex.isra.1 () from /lib64/libpython3.4m.so.1.0
#96 0x00007fc52c5500a4 in PyEval_EvalFrameEx () from /lib64/libpython3.4m.so.1.0
#97 0x00007fc52c555450 in PyEval_EvalFrameEx () from /lib64/libpython3.4m.so.1.0
#98 0x00007fc52c555450 in PyEval_EvalFrameEx () from /lib64/libpython3.4m.so.1.0
#99 0x00007fc52c55654e in PyEval_EvalCodeEx () from /lib64/libpython3.4m.so.1.0
#100 0x00007fc52c554022 in PyEval_EvalFrameEx () from /lib64/libpython3.4m.so.1.0
#101 0x00007fc52c55654e in PyEval_EvalCodeEx () from /lib64/libpython3.4m.so.1.0
#102 0x00007fc52c554022 in PyEval_EvalFrameEx () from /lib64/libpython3.4m.so.1.0
#103 0x00007fc52c55654e in PyEval_EvalCodeEx () from /lib64/libpython3.4m.so.1.0
#104 0x00007fc52c554022 in PyEval_EvalFrameEx () from /lib64/libpython3.4m.so.1.0
#105 0x00007fc52c55654e in PyEval_EvalCodeEx () from /lib64/libpython3.4m.so.1.0
#106 0x00007fc52c554022 in PyEval_EvalFrameEx () from /lib64/libpython3.4m.so.1.0
#107 0x00007fc52c55654e in PyEval_EvalCodeEx () from /lib64/libpython3.4m.so.1.0
#108 0x00007fc52c4c66a3 in function_call () from /lib64/libpython3.4m.so.1.0
#109 0x00007fc52c49ddcc in PyObject_Call () from /lib64/libpython3.4m.so.1.0
#110 0x00007fc52c551dd9 in PyEval_EvalFrameEx () from /lib64/libpython3.4m.so.1.0
#111 0x00007fc52c55654e in PyEval_EvalCodeEx () from /lib64/libpython3.4m.so.1.0
#112 0x00007fc52c4c65ae in function_call () from /lib64/libpython3.4m.so.1.0
#113 0x00007fc52c49ddcc in PyObject_Call () from /lib64/libpython3.4m.so.1.0
#114 0x00007fc52c49ea1c in PyObject_CallFunctionObjArgs () from /lib64/libpython3.4m.so.1.0
#115 0x00007fc52a94c087 in WraptBoundFunctionWrapper_call (self=0x7fc525f6a048, args=<optimized out>, kwds=0x7fc525f7fe88) at src/wrapt/_wrappers.c:2400
#116 0x00007fc52c49ddcc in PyObject_Call () from /lib64/libpython3.4m.so.1.0
#117 0x00007fc52c550f12 in PyEval_EvalFrameEx () from /lib64/libpython3.4m.so.1.0
#118 0x00007fc52c55654e in PyEval_EvalCodeEx () from /lib64/libpython3.4m.so.1.0
#119 0x00007fc52c4c66a3 in function_call () from /lib64/libpython3.4m.so.1.0
#120 0x00007fc52c49ddcc in PyObject_Call () from /lib64/libpython3.4m.so.1.0
#121 0x00007fc52c551dd9 in PyEval_EvalFrameEx () from /lib64/libpython3.4m.so.1.0
#122 0x00007fc52c4bf8ff in gen_send_ex.isra.1 () from /lib64/libpython3.4m.so.1.0
#123 0x00007fc52c5500a4 in PyEval_EvalFrameEx () from /lib64/libpython3.4m.so.1.0
#124 0x00007fc52c4bf8ff in gen_send_ex.isra.1 () from /lib64/libpython3.4m.so.1.0
#125 0x00007fc52c5500a4 in PyEval_EvalFrameEx () from /lib64/libpython3.4m.so.1.0
---Type <return> to continue, or q <return> to quit---
#126 0x00007fc52c4bf8ff in gen_send_ex.isra.1 () from /lib64/libpython3.4m.so.1.0
#127 0x00007fc52c5500a4 in PyEval_EvalFrameEx () from /lib64/libpython3.4m.so.1.0
#128 0x00007fc52c4bf8ff in gen_send_ex.isra.1 () from /lib64/libpython3.4m.so.1.0
#129 0x00007fc52c5500a4 in PyEval_EvalFrameEx () from /lib64/libpython3.4m.so.1.0
#130 0x00007fc52c4bf8ff in gen_send_ex.isra.1 () from /lib64/libpython3.4m.so.1.0
#131 0x00007fc52c5500a4 in PyEval_EvalFrameEx () from /lib64/libpython3.4m.so.1.0
#132 0x00007fc52c4bf8ff in gen_send_ex.isra.1 () from /lib64/libpython3.4m.so.1.0
#133 0x00007fc52c5500a4 in PyEval_EvalFrameEx () from /lib64/libpython3.4m.so.1.0
#134 0x00007fc52c4bf8ff in gen_send_ex.isra.1 () from /lib64/libpython3.4m.so.1.0
#135 0x00007fc52c5500a4 in PyEval_EvalFrameEx () from /lib64/libpython3.4m.so.1.0
#136 0x00007fc52c4bf8ff in gen_send_ex.isra.1 () from /lib64/libpython3.4m.so.1.0
#137 0x00007fc52c5500a4 in PyEval_EvalFrameEx () from /lib64/libpython3.4m.so.1.0
#138 0x00007fc52c4bf8ff in gen_send_ex.isra.1 () from /lib64/libpython3.4m.so.1.0
#139 0x00007fc52c5500a4 in PyEval_EvalFrameEx () from /lib64/libpython3.4m.so.1.0
#140 0x00007fc52c4bf8ff in gen_send_ex.isra.1 () from /lib64/libpython3.4m.so.1.0
#141 0x00007fc52c5500a4 in PyEval_EvalFrameEx () from /lib64/libpython3.4m.so.1.0
#142 0x00007fc52c4bf8ff in gen_send_ex.isra.1 () from /lib64/libpython3.4m.so.1.0
#143 0x00007fc52c5500a4 in PyEval_EvalFrameEx () from /lib64/libpython3.4m.so.1.0
#144 0x00007fc52c4bf8ff in gen_send_ex.isra.1 () from /lib64/libpython3.4m.so.1.0
#145 0x00007fc52c5500a4 in PyEval_EvalFrameEx () from /lib64/libpython3.4m.so.1.0
#146 0x00007fc52c4bf8ff in gen_send_ex.isra.1 () from /lib64/libpython3.4m.so.1.0
#147 0x00007fc52c5500a4 in PyEval_EvalFrameEx () from /lib64/libpython3.4m.so.1.0
#148 0x00007fc52c4bf8ff in gen_send_ex.isra.1 () from /lib64/libpython3.4m.so.1.0
#149 0x00007fc52c5500a4 in PyEval_EvalFrameEx () from /lib64/libpython3.4m.so.1.0
#150 0x00007fc52c4bf8ff in gen_send_ex.isra.1 () from /lib64/libpython3.4m.so.1.0
#151 0x00007fc52c5500a4 in PyEval_EvalFrameEx () from /lib64/libpython3.4m.so.1.0
#152 0x00007fc52c4bf8ff in gen_send_ex.isra.1 () from /lib64/libpython3.4m.so.1.0
#153 0x00007fc52c5500a4 in PyEval_EvalFrameEx () from /lib64/libpython3.4m.so.1.0
#154 0x00007fc52c4bf8ff in gen_send_ex.isra.1 () from /lib64/libpython3.4m.so.1.0
#155 0x00007fc52c5500a4 in PyEval_EvalFrameEx () from /lib64/libpython3.4m.so.1.0
#156 0x00007fc52c4bf8ff in gen_send_ex.isra.1 () from /lib64/libpython3.4m.so.1.0
#157 0x00007fc52c5500a4 in PyEval_EvalFrameEx () from /lib64/libpython3.4m.so.1.0
#158 0x00007fc52c555450 in PyEval_EvalFrameEx () from /lib64/libpython3.4m.so.1.0
#159 0x00007fc52c555450 in PyEval_EvalFrameEx () from /lib64/libpython3.4m.so.1.0
#160 0x00007fc52c55654e in PyEval_EvalCodeEx () from /lib64/libpython3.4m.so.1.0
#161 0x00007fc52c554022 in PyEval_EvalFrameEx () from /lib64/libpython3.4m.so.1.0
#162 0x00007fc52c55654e in PyEval_EvalCodeEx () from /lib64/libpython3.4m.so.1.0
#163 0x00007fc52c554022 in PyEval_EvalFrameEx () from /lib64/libpython3.4m.so.1.0
#164 0x00007fc52c555450 in PyEval_EvalFrameEx () from /lib64/libpython3.4m.so.1.0
#165 0x00007fc52c55654e in PyEval_EvalCodeEx () from /lib64/libpython3.4m.so.1.0
#166 0x00007fc52c554022 in PyEval_EvalFrameEx () from /lib64/libpython3.4m.so.1.0
#167 0x00007fc52c555450 in PyEval_EvalFrameEx () from /lib64/libpython3.4m.so.1.0
#168 0x00007fc52c55654e in PyEval_EvalCodeEx () from /lib64/libpython3.4m.so.1.0
#169 0x00007fc52c4c65ae in function_call () from /lib64/libpython3.4m.so.1.0
#170 0x00007fc52c49ddcc in PyObject_Call () from /lib64/libpython3.4m.so.1.0
#171 0x00007fc52c4b2e9d in method_call () from /lib64/libpython3.4m.so.1.0
#172 0x00007fc52c49ddcc in PyObject_Call () from /lib64/libpython3.4m.so.1.0
#173 0x00007fc52c4f5f90 in slot_tp_init () from /lib64/libpython3.4m.so.1.0
#174 0x00007fc52c4f39c6 in type_call () from /lib64/libpython3.4m.so.1.0
#175 0x00007fc52c49ddcc in PyObject_Call () from /lib64/libpython3.4m.so.1.0
#176 0x00007fc52c550f12 in PyEval_EvalFrameEx () from /lib64/libpython3.4m.so.1.0
#177 0x00007fc52c555450 in PyEval_EvalFrameEx () from /lib64/libpython3.4m.so.1.0
#178 0x00007fc52c55654e in PyEval_EvalCodeEx () from /lib64/libpython3.4m.so.1.0
#179 0x00007fc52c55661b in PyEval_EvalCode () from /lib64/libpython3.4m.so.1.0
#180 0x00007fc52c5726c4 in run_mod () from /lib64/libpython3.4m.so.1.0
#181 0x00007fc52c574c0d in PyRun_FileExFlags () from /lib64/libpython3.4m.so.1.0
#182 0x00007fc52c5763d1 in PyRun_SimpleFileExFlags () from /lib64/libpython3.4m.so.1.0
#183 0x00007fc52c58bdfc in Py_Main () from /lib64/libpython3.4m.so.1.0
#184 0x0000000000400ad9 in main ()
```

**Comment by zmedico** [comment]
Same as https://github.com/google/protobuf/issues/2974, fixed by https://github.com/google/protobuf/pull/4365.

**Comment by anandolee** [comment]
It fixed in google internal code by @amauryfa. 
Expect to see the fix in next release. I will close this for clean up, feel free to reopen it if it is still an issue after next release.
