### ISSUE TITLE
Failed to build 'google-protobuf.js' with command 'gulp dist'

### ISSUE THREAD

**Issue by JiekeZhu** [google/protobuf#3188]
Hi there,
I'm trying to use the commonjs imports in my project. So I follow the step to build the google-protobuf.js file. But I failed. And I have no idea about how to fix this. Please give some advise. Thanks in advance.

gulp dist
[Timestamp] Using gulpfile xxxx\protobuf-3.3.0\js\gulpfile.js
[Timestamp] Starting 'genproto_wellknowntypes'...
[Timestamp] 'genproto_wellknowntypes' errored after 6.3 ms
[Timestamp] Error: spawn sh ENOENT
    at exports._errnoException (util.js:1018:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:367:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
    at Module.runMain (module.js:606:11)
    at run (bootstrap_node.js:390:7)
    at startup (bootstrap_node.js:150:9)
    at bootstrap_node.js:505:3

Br,
Jieke

**Comment by AndrewBrough** [comment]
I'm encountering the same issue. Manually downloaded protobuf-3.4.0. I'm seeing this when I run

$ npm test

> google-protobuf@3.4.0 test C:\Users\andre\Documents\protobuf-3.4.0\js
> node ./node_modules/gulp/bin/gulp.js test

[09:58:48] Using gulpfile ~\Documents\protobuf-3.4.0\js\gulpfile.js
[09:58:48] Starting 'genproto_well_known_types_closure'...
[09:58:48] Starting 'genproto_group1_closure'...
[09:58:48] Starting 'genproto_group2_closure'...
[09:58:48] Starting 'genproto_wellknowntypes'...
[09:58:48] Starting 'genproto_well_known_types_commonjs'...
[09:58:48] Starting 'genproto_group1_commonjs'...
[09:58:48] Starting 'genproto_group2_commonjs'...
[09:58:48] Starting 'genproto_commonjs_wellknowntypes'...
[09:58:48] Starting 'commonjs_asserts'...
[09:58:48] Starting 'commonjs_testdeps'...


[09:58:48] 'genproto_well_known_types_closure' errored after 36 ms
[09:58:48] Error: spawn sh ENOENT
    at exports._errnoException (util.js:1018:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:367:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
    at Module.runMain (module.js:606:11)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:504:3

Very stuck here, also can't get this to work in my own project.

**Comment by haberman** [comment]
Did you build or download `protoc` first? The first thing you need to do is run `./configure && make` in the base directory.

It is unfortunate that the error message is so unhelpful here. What OS are you running on?

**Comment by AndrewBrough** [comment]
I've managed to get past this today, however it was quite frustrating.


I'm running Windows 10, and I did manage to get the tests completing
successfully by modifying the path to protoc in gulpfile.js line 9

var protoc = process.env.PROTOC || '../src/protoc/bin/protoc.exe';

and also only able to successfully run $ npm test from a different command
shell, MINGW64, which was included with my git installation. Cmd and
powershell fail every time with the previous error I posted.

**Comment by haberman** [comment]
Sorry for the frustration. Yes all of those commands were written and tested under Linux and OS X. For Windows I would recommend doing `npm install` of google-protobuf instead of installing from protobuf releases. The npm package contains `google-protobuf.js` and all of the well-known types as prebuilt .js files, so calling `protoc` is not required.
