### ISSUE TITLE
Dealing with duplicate protobuf descriptor names

### ISSUE THREAD

**Issue by achow101** [google/protobuf#3272]
I have an issue where I am trying to use two libraries that happen to also use the same protobuf descriptor names and fields. I can't change the libraries to not use the same names but I also need to use both libraries in my application. What is the best way for me to handle this?

I'm using python.

**Comment by xfxyjwf** [comment]
Unfortunately I don't think there is any way to work around this kind of conflict. One of them have to be renamed or put in a different package.  What are the two libraries? Can you ask if their maintainers can help with it?

**Comment by achow101** [comment]
The two libraries are https://github.com/trezor/python-trezor and https://github.com/keepkey/python-keepkey.

What do you mean by "different package"?

**Comment by xfxyjwf** [comment]
When I said "different package", I meant exactly what you did (adding a "package" declaration in the .proto file). That should work as far as I can tell. What error did you see after adding these packages?

**Comment by achow101** [comment]
I receive this error
```
Traceback (most recent call last):
  File "ArmoryQt.py", line 66, in <module>
    from qtdialogs import *
  File "/home/andy/BitcoinArmory/qtdialogs.py", line 11750, in <module>
    from ui.WalletImportRestore import DlgUniversalRestoreSelect, DlgRestoreSingle, \
  File "/home/andy/BitcoinArmory/ui/WalletImportRestore.py", line 16, in <module>
    from armoryengine.KeepKeyHW import DlgChooseKeepKey
  File "/home/andy/BitcoinArmory/armoryengine/KeepKeyHW.py", line 5, in <module>
    from keepkeylib.client import KeepKeyClient
  File "/usr/local/lib/python2.7/dist-packages/keepkey-0.8.0-py2.7.egg/keepkeylib/client.py", line 36, in <module>
    from . import mapping
  File "/usr/local/lib/python2.7/dist-packages/keepkey-0.8.0-py2.7.egg/keepkeylib/mapping.py", line 1, in <module>
    from . import messages_pb2 as proto
  File "/usr/local/lib/python2.7/dist-packages/keepkey-0.8.0-py2.7.egg/keepkeylib/messages_pb2.py", line 17, in <module>
    import types_pb2 as types__pb2
  File "/usr/local/lib/python2.7/dist-packages/keepkey-0.8.0-py2.7.egg/keepkeylib/types_pb2.py", line 27, in <module>
    dependencies=[google_dot_protobuf_dot_descriptor__pb2.DESCRIPTOR,exchange__pb2.DESCRIPTOR,])
  File "/usr/local/lib/python2.7/dist-packages/google/protobuf/descriptor.py", line 824, in __new__
    return _message.default_pool.AddSerializedFile(serialized_pb)
TypeError: Couldn't build proto file into descriptor pool!
Invalid proto descriptor for file "types.proto":
  types.proto: A file with this name is already in the pool.
```

This is after I changed the `.proto` files to have a package declaration, compiled the files, and installed the python library. I also double checked that the installed python library has the `_pb2.py` files with the package declaration.

**Comment by xfxyjwf** [comment]
Oh, you can't have files with the same name either... Both repository have a types.proto file.

**Comment by achow101** [comment]
Ok.. I have gone through and changed all of their names. Now I get yet another error:
```
Traceback (most recent call last):
  File "ArmoryQt.py", line 66, in <module>
    from qtdialogs import *
  File "/home/andy/BitcoinArmory/qtdialogs.py", line 11750, in <module>
    from ui.WalletImportRestore import DlgUniversalRestoreSelect, DlgRestoreSingle, \
  File "/home/andy/BitcoinArmory/ui/WalletImportRestore.py", line 16, in <module>
    from armoryengine.KeepKeyHW import DlgChooseKeepKey
  File "/home/andy/BitcoinArmory/armoryengine/KeepKeyHW.py", line 5, in <module>
    from keepkeylib.client import KeepKeyClient
  File "/usr/local/lib/python2.7/dist-packages/keepkey-0.8.0-py2.7.egg/keepkeylib/client.py", line 36, in <module>
    from . import mapping
  File "/usr/local/lib/python2.7/dist-packages/keepkey-0.8.0-py2.7.egg/keepkeylib/mapping.py", line 1, in <module>
    from . import messages_keepkey_pb2 as proto
  File "/usr/local/lib/python2.7/dist-packages/keepkey-0.8.0-py2.7.egg/keepkeylib/messages_keepkey_pb2.py", line 17, in <module>
    import types_keepkey_pb2 as types__keepkey__pb2
  File "/usr/local/lib/python2.7/dist-packages/keepkey-0.8.0-py2.7.egg/keepkeylib/types_keepkey_pb2.py", line 1435, in <module>
    google_dot_protobuf_dot_descriptor__pb2.EnumValueOptions.RegisterExtension(wire_in)
ValueError: Double registration of Extensions
```

**Comment by xfxyjwf** [comment]
Apparently these two proto files are either forking from the same source or they are forking from each other. They have the same custom option definitions:
https://github.com/trezor/trezor-common/blob/master/protob/types.proto#L18
https://github.com/keepkey/device-protocol/blob/master/types.proto#L18

Their field numbers need to be updated in order to avoid conflict.

**Comment by achow101** [comment]
Ok. Thank you for your help.

**Comment by Syndace** [comment]
Uhm I'm sorry, but how can this be closed just like that? You can't expect every Python package in existence to magically use different file names for their schemas. In fact it should be absolutely fine for Python packages to define the same structures with the same extensions under the same file names - that's what the package/import system is for.

**Comment by Benjoyo** [comment]
The amount of issues you run into using protobuf is amazing...
