### ISSUE TITLE
Java NoSuchMethodError v3.3.1

### ISSUE THREAD

**Issue by ElectroLutz** [google/protobuf#3499]
Hey,

I'm experiencing the following error using version 3.3.1 of protobuf java and 3.3.0 of protoc.

> java.lang.NoSuchMethodError: com.google.protobuf.Descriptors$FileDescriptor.getSyntax()Lcom/google/protobuf/Descriptors$FileDescriptor$Syntax;
	at com.google.protobuf.GeneratedMessageV3$FieldAccessorTable.supportFieldPresence(GeneratedMessageV3.java:1895)
	at com.google.protobuf.GeneratedMessageV3$FieldAccessorTable.access$1200(GeneratedMessageV3.java:1678)
	at com.google.protobuf.GeneratedMessageV3$FieldAccessorTable$SingularFieldAccessor.<init>(GeneratedMessageV3.java:1908)
	at com.google.protobuf.GeneratedMessageV3$FieldAccessorTable$SingularStringFieldAccessor.<init>(GeneratedMessageV3.java:2526)
	at com.google.protobuf.GeneratedMessageV3$FieldAccessorTable.ensureFieldAccessorsInitialized(GeneratedMessageV3.java:1760)
	at com.sixt.protobuf.Foobar.internalGetFieldAccessorTable(Foobar.java:77)
	at com.google.protobuf.GeneratedMessageV3.getAllFieldsMutable(GeneratedMessageV3.java:134)
	at com.google.protobuf.GeneratedMessageV3.getAllFields(GeneratedMessageV3.java:210)
	at com.google.protobuf.TextFormat$Printer.print(TextFormat.java:298)
	at com.google.protobuf.TextFormat$Printer.access$400(TextFormat.java:273)
	at com.google.protobuf.TextFormat.print(TextFormat.java:76)
	at com.google.protobuf.TextFormat.printToString(TextFormat.java:143)
	at com.google.protobuf.AbstractMessage.toString(AbstractMessage.java:79)

foobar.proto looks like this:

```
syntax = "proto3";

option java_package = "com.company.protobuf";
option java_multiple_files = true;

message Foobar {
    string name = 1;
    int64 nummer = 2;
}
```

What am I doing wrong?

**Comment by pherl** [comment]
Do you have multiple protobuf runtime available on the class path? I see there might be two reasons:
- the 3.3.1 broke the compatibility test and we didn't catch it
- the runtime itself was loaded from different versions which is not compatible with each other.

Feng, do we have test for 3.3.1 vs 3.3.0 protoc?

**Comment by xfxyjwf** [comment]
There is no Java runtime or generated code change between 3.3.1 and 3.3.0. The only diff is the guava dependency of protobuf-java-util has been downgraded to 19 but that shouldn't affect the core library at all.

I suspect the problem is that you have some other version of protobuf on your class path.

**Comment by ElectroLutz** [comment]
There was really another protobuf I didn't know of. Sorry for the inconvenience.
