### ISSUE TITLE
TextFormat: parsing recursive maps throws NullPointerException

### ISSUE THREAD

**Issue by thesamet** [google/protobuf#355]
Example proto:

```
syntax = "proto3";

option java_package="com.thesamet";

message Bar {
  map<int32, Bar> m = 1;  // value type is the same type as containing message.
  int32 k = 2;
}
```

Example code:

```
import com.thesamet.*;
import com.google.protobuf.*;

public class Hello {
    static public void main(String[] args) throws TextFormat.ParseException {

        Test.Bar.Builder barBuilder = Test.Bar.newBuilder();
        TextFormat.merge(
            "m {\n" +
            "  key: 17\n" +
            "  value: {\n" +
            "  }\n" + 
            "}\n",

            barBuilder);

        System.out.println(barBuilder.build());
    }
}
```

Exception:

```
Exception in thread "main" java.lang.NullPointerException
        at com.google.protobuf.MapEntry$Builder.newBuilderForField(MapEntry.java:315)
        at com.google.protobuf.MessageReflection$BuilderAdapter.newMergeTargetForField(MessageReflection.java:513)
        at com.google.protobuf.TextFormat$Parser.consumeFieldValue(TextFormat.java:1454)
        at com.google.protobuf.TextFormat$Parser.mergeField(TextFormat.java:1421)
        at com.google.protobuf.TextFormat$Parser.consumeFieldValue(TextFormat.java:1462)
        at com.google.protobuf.TextFormat$Parser.mergeField(TextFormat.java:1421)
        at com.google.protobuf.TextFormat$Parser.merge(TextFormat.java:1303)
        at com.google.protobuf.TextFormat$Parser.merge(TextFormat.java:1246)
        at com.google.protobuf.TextFormat.merge(TextFormat.java:1136)
        at Hello.main(Hello.java:11)
```

**Comment by xfxyjwf** [comment]
I checked the latest version (v3.2.0) and the problem no longer exists.
