### ISSUE TITLE
some errors about protobuf when run channel pruning

### ISSUE THREAD

**Issue by yewuyue111** [google/protobuf#3765]
Hi.
I had install protobuf3.2 with pip,and I make caffe done,also I can test the VGG net with ILSVRC.
But when I run channel pruning(the code by yihui he),I got this error:
(python3.5) tang@tang:~/channel-pruning$ python train.py -action c3 -caffe 0
no lighting pack
[libprotobuf INFO google/protobuf/io/coded_stream.cc:610] Reading dangerously large protocol message.  If the message turns out to be larger than 2147483647 bytes, parsing will be halted for security reasons.  To increase the limit (or to disable these warnings), see CodedInputStream::SetTotalBytesLimit() in google/protobuf/io/coded_stream.h.
[libprotobuf WARNING google/protobuf/io/coded_stream.cc:81] The total number of bytes read was 553432081
Process Process-1:
Traceback (most recent call last):
  File "/home/tang/anaconda3/envs/python3.5/lib/python3.5/multiprocessing/process.py", line 252, in _bootstrap
    self.run()
  File "/home/tang/anaconda3/envs/python3.5/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/tang/channel-pruning/lib/worker.py", line 21, in job
    ret = target(**kwargs)
  File "train.py", line 26, in step0
    net = Net(pt, model=model, noTF=1)
  File "/home/tang/channel-pruning/lib/net.py", line 68, in __init__
    self.net_param = NetBuilder(pt=pt)
  File "/home/tang/channel-pruning/lib/builder.py", line 132, in __init__
    pb2.Merge(f.read(), self.net)
  File "/home/tang/anaconda3/envs/python3.5/lib/python3.5/site-packages/google/protobuf/text_format.py", line 476, in Merge
    descriptor_pool=descriptor_pool)
  File "/home/tang/anaconda3/envs/python3.5/lib/python3.5/site-packages/google/protobuf/text_format.py", line 526, in MergeLines
    return parser.MergeLines(lines, message)
  File "/home/tang/anaconda3/envs/python3.5/lib/python3.5/site-packages/google/protobuf/text_format.py", line 559, in MergeLines
    self._ParseOrMerge(lines, message)
  File "/home/tang/anaconda3/envs/python3.5/lib/python3.5/site-packages/google/protobuf/text_format.py", line 574, in _ParseOrMerge
    self._MergeField(tokenizer, message)
  File "/home/tang/anaconda3/envs/python3.5/lib/python3.5/site-packages/google/protobuf/text_format.py", line 675, in _MergeField
    merger(tokenizer, message, field)
  File "/home/tang/anaconda3/envs/python3.5/lib/python3.5/site-packages/google/protobuf/text_format.py", line 764, in _MergeMessageField
    self._MergeField(tokenizer, sub_message)
  File "/home/tang/anaconda3/envs/python3.5/lib/python3.5/site-packages/google/protobuf/text_format.py", line 675, in _MergeField
    merger(tokenizer, message, field)
  File "/home/tang/anaconda3/envs/python3.5/lib/python3.5/site-packages/google/protobuf/text_format.py", line 764, in _MergeMessageField
    self._MergeField(tokenizer, sub_message)
  File "/home/tang/anaconda3/envs/python3.5/lib/python3.5/site-packages/google/protobuf/text_format.py", line 675, in _MergeField
    merger(tokenizer, message, field)
  File "/home/tang/anaconda3/envs/python3.5/lib/python3.5/site-packages/google/protobuf/text_format.py", line 809, in _MergeScalarField
    value = tokenizer.ConsumeString()
  File "/home/tang/anaconda3/envs/python3.5/lib/python3.5/site-packages/google/protobuf/text_format.py", line 1151, in ConsumeString
    the_bytes = self.ConsumeByteString()
  File "/home/tang/anaconda3/envs/python3.5/lib/python3.5/site-packages/google/protobuf/text_format.py", line 1166, in ConsumeByteString
    the_list = [self._ConsumeSingleByteString()]
  File "/home/tang/anaconda3/envs/python3.5/lib/python3.5/site-packages/google/protobuf/text_format.py", line 1191, in _ConsumeSingleByteString
    result = text_encoding.CUnescape(text[1:-1])
  File "/home/tang/anaconda3/envs/python3.5/lib/python3.5/site-packages/google/protobuf/text_encoding.py", line 103, in CUnescape
    result = ''.join(_cescape_highbit_to_str[ord(c)] for c in result)
  File "/home/tang/anaconda3/envs/python3.5/lib/python3.5/site-packages/google/protobuf/text_encoding.py", line 103, in <genexpr>
    result = ''.join(_cescape_highbit_to_str[ord(c)] for c in result)
IndexError: list index out of range

I want to know which may take this error.
Thanks.

**Comment by yewuyue111** [comment]
I have solved this problem.
Because the path of ILSVRC has Chinese in it.
Sorry about this.

**Comment by benjaminku** [comment]
I have some problems ,can anyone help me to solve it. thanks

(tensorflow1) C:\tensorflow1\models\research\object_detection>python train.py --logtostderr --train_dir=training/ --pipeline_config_path=training/faster_rcnn_inception_v2_pets.config
WARNING:tensorflow:From C:\Users\User\Anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\python\platform\app.py:124: main (from __main__) is deprecated and will be removed in a future version.
Instructions for updating:
Use object_detection/model_main.py.
Traceback (most recent call last):
  File "train.py", line 184, in <module>
    tf.app.run()
  File "C:\Users\User\Anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\python\platform\app.py", line 124, in run
    _sys.exit(main(argv))
  File "C:\Users\User\Anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\python\util\deprecation.py", line 136, in new_func
    return func(*args, **kwargs)
  File "train.py", line 93, in main
    FLAGS.pipeline_config_path)
  File "C:\tensorflow1\models\research\object_detection\utils\config_util.py", line 98, in get_configs_from_pipeline_file
    text_format.Merge(proto_str, pipeline_config)
  File "C:\Users\User\Anaconda3\envs\tensorflow1\lib\site-packages\google\protobuf\text_format.py", line 536, in Merge
    descriptor_pool=descriptor_pool)
  File "C:\Users\User\Anaconda3\envs\tensorflow1\lib\site-packages\google\protobuf\text_format.py", line 590, in MergeLines
    return parser.MergeLines(lines, message)
  File "C:\Users\User\Anaconda3\envs\tensorflow1\lib\site-packages\google\protobuf\text_format.py", line 623, in MergeLines
    self._ParseOrMerge(lines, message)
  File "C:\Users\User\Anaconda3\envs\tensorflow1\lib\site-packages\google\protobuf\text_format.py", line 638, in _ParseOrMerge
    self._MergeField(tokenizer, message)
  File "C:\Users\User\Anaconda3\envs\tensorflow1\lib\site-packages\google\protobuf\text_format.py", line 763, in _MergeField
    merger(tokenizer, message, field)
  File "C:\Users\User\Anaconda3\envs\tensorflow1\lib\site-packages\google\protobuf\text_format.py", line 837, in _MergeMessageField
    self._MergeField(tokenizer, sub_message)
  File "C:\Users\User\Anaconda3\envs\tensorflow1\lib\site-packages\google\protobuf\text_format.py", line 763, in _MergeField
    merger(tokenizer, message, field)
  File "C:\Users\User\Anaconda3\envs\tensorflow1\lib\site-packages\google\protobuf\text_format.py", line 888, in _MergeScalarField
    value = tokenizer.ConsumeString()
  File "C:\Users\User\Anaconda3\envs\tensorflow1\lib\site-packages\google\protobuf\text_format.py", line 1251, in ConsumeString
    the_bytes = self.ConsumeByteString()
  File "C:\Users\User\Anaconda3\envs\tensorflow1\lib\site-packages\google\protobuf\text_format.py", line 1266, in ConsumeByteString
    the_list = [self._ConsumeSingleByteString()]
  File "C:\Users\User\Anaconda3\envs\tensorflow1\lib\site-packages\google\protobuf\text_format.py", line 1291, in _ConsumeSingleByteString
    result = text_encoding.CUnescape(text[1:-1])
  File "C:\Users\User\Anaconda3\envs\tensorflow1\lib\site-packages\google\protobuf\text_encoding.py", line 103, in CUnescape
    result = ''.join(_cescape_highbit_to_str[ord(c)] for c in result)
  File "C:\Users\User\Anaconda3\envs\tensorflow1\lib\site-packages\google\protobuf\text_encoding.py", line 103, in <genexpr>
    result = ''.join(_cescape_highbit_to_str[ord(c)] for c in result)
IndexError: list index out of range
