### ISSUE TITLE
Use io.netty-4.1.20.Final to integate protbuf-3.5.1

### ISSUE THREAD

**Issue by xyxiaoyou** [google/protobuf#4213]
com.google.protobuf.InvalidProtocolBufferException: While parsing a protocol message, the input ended unexpectedly in the middle of a field.  This could mean either that the input has been truncated or that an embedded message misreported its own length.
......
......
......
Caused by: com.google.protobuf.InvalidProtocolBufferException: While parsing a protocol message, the input ended unexpectedly in the middle of a field.  This could mean either that the input has been truncated or that an embedded message misreported its own length.
	at com.google.protobuf.InvalidProtocolBufferException.truncatedMessage(InvalidProtocolBufferException.java:86)
	at com.google.protobuf.CodedInputStream$ArrayDecoder.readRawBytes(CodedInputStream.java:1281)
	at com.google.protobuf.CodedInputStream$ArrayDecoder.readBytes(CodedInputStream.java:935)
	at com.google.protobuf.UnknownFieldSet$Builder.mergeFieldFrom(UnknownFieldSet.java:537)
	at com.google.protobuf.GeneratedMessageV3.parseUnknownField(GeneratedMessageV3.java:293)
	at protobuf.PacketProto$Packet.<init>(PacketProto.java:173)
	at protobuf.PacketProto$Packet.<init>(PacketProto.java:135)
	at protobuf.PacketProto$Packet$1.parsePartialFrom(PacketProto.java:1851)
	at protobuf.PacketProto$Packet$1.parsePartialFrom(PacketProto.java:1846)
	at com.google.protobuf.AbstractParser.parsePartialFrom(AbstractParser.java:163)
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:197)
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:203)
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:49)
	at io.netty.handler.codec.protobuf.ProtobufDecoder.decode(ProtobufDecoder.java:121)
	at io.netty.handler.codec.protobuf.ProtobufDecoder.decode(ProtobufDecoder.java:64)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88)

**Comment by acozzette** [comment]
@xyxiaoyou It sounds like there was just a malformed serialized proto--are you sure there is a bug here?

**Comment by xyxiaoyou** [comment]
The problem has been solved.     My fault.

**Comment by thinkerou** [comment]
@xyxiaoyou what's question? thanks!

**Comment by mahendratonape** [comment]
i am having client application which is continuously publishing message through zeroMQ publisher, i am successfully getting data by subscribing to client publisher but  after receiving few messages i am getting  invalidProtocolBufferException any solution to this

**Comment by Praveenkh88** [comment]
@[xyxiaoyou](/xyxiaoyou) what was the fault and how did you resolved it.
