### ISSUE TITLE
Failed to run cythonized grpc code: TypeError: Descriptors should not be created directly, but only retrieved from their parent.

### ISSUE THREAD

**Issue by bigquant** [google/protobuf#4231]
OS: ubuntu 16.04
python: 3.5.2

```
sudo pip3 install cython==0.27.3 grpcio==1.8.4

git clone https://github.com/grpc/grpc.git
cd grpc/examples/python/helloworld

cythonize -i helloworld_pb2*

python3 greeter_server.py

```

and it shows errors

```
Traceback (most recent call last):
  File "greeter_server.py", line 21, in <module>
    import helloworld_pb2
  File "helloworld_pb2.py", line 35, in init helloworld_pb2 (/src/grpc/examples/python/helloworld/helloworld_pb2.c:1917)
    _descriptor.FieldDescriptor(
  File "/usr/local/lib/python3.5/dist-packages/google/protobuf/descriptor.py", line 497, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors should not be created directly, but only retrieved from their parent.
```

from https://github.com/grpc/grpc/issues/14111

**Comment by arthur-tacca** [comment]
I reported this in #2896. As you can see from the example call stacks in that report, there isn't an obvious way to adapt this check to Cythoned protobufs. As I said in that report, I would be in favor of removing the check altogether.

**Comment by anandolee** [comment]
Closing it because it is duplicate with #2896.
