### ISSUE TITLE
when I serialize the pb data occured the exception: UnpairedSurrogateException

### ISSUE THREAD

**Issue by xiaodin1** [google/protobuf#4268]
[code] :
bufferToEmit = data.build().toByteArray();
[exception]:
2018-02-02 19:09:16.430 **STDIO [ERROR]** Feb 02, 2018 7:09:16 PM com.google.protobuf.CodedOutputStream inefficientWriteStringNoTag
WARNING: Converting ill-formed UTF-16. Your Protocol Buffer will not round trip correctly!
com.google.protobuf.Utf8$UnpairedSurrogateException: Unpaired surrogate at index 45 of 133
        at com.google.protobuf.Utf8$UnsafeProcessor.encodeUtf8(Utf8.java:1227)
        at com.google.protobuf.Utf8.encode(Utf8.java:304)
        at com.google.protobuf.CodedOutputStream$ArrayEncoder.writeStringNoTag(CodedOutputStream.java:1461)
        at com.google.protobuf.FieldSet.writeElementNoTag(FieldSet.java:685)
        at com.google.protobuf.FieldSet.writeElement(FieldSet.java:652)
        at com.google.protobuf.MapEntryLite.writeTo(MapEntryLite.java:112)
        at com.google.protobuf.MapEntry.writeTo(MapEntry.java:153)
        at com.google.protobuf.CodedOutputStream$ArrayEncoder.writeMessageNoTag(CodedOutputStream.java:1298)
        at com.google.protobuf.CodedOutputStream$ArrayEncoder.writeMessage(CodedOutputStream.java:1274)
        at com.google.protobuf.GeneratedMessageV3.serializeMapTo(GeneratedMessageV3.java:2835)
        at com.google.protobuf.GeneratedMessageV3.serializeStringMapTo(GeneratedMessageV3.java:2778)
        at com.baidu.cloudids.proto.HttpIdsPb$MsgDictStrList.writeTo(HttpIdsPb.java:1709)
        at com.google.protobuf.CodedOutputStream$ArrayEncoder.writeMessageNoTag(CodedOutputStream.java:1298)
        at com.google.protobuf.CodedOutputStream$ArrayEncoder.writeMessage(CodedOutputStream.java:1274)
        at com.baidu.cloudids.proto.HttpIdsPb$MsgHttpReq.writeTo(HttpIdsPb.java:3191)
        at com.google.protobuf.CodedOutputStream$ArrayEncoder.writeMessageNoTag(CodedOutputStream.java:1298)
        at com.google.protobuf.CodedOutputStream$ArrayEncoder.writeMessage(CodedOutputStream.java:1274)
        at com.baidu.cloudids.proto.HttpIdsPb$MsgHttpContext.writeTo(HttpIdsPb.java:7015)
        at com.google.protobuf.AbstractMessageLite.toByteArray(AbstractMessageLite.java:70)

**Comment by xfxyjwf** [comment]
Can you attach the output of data.build().toString()?

**Comment by xiaodin1** [comment]
Is there any way help me easy to catch the exception so that i can easily get the data.

**Comment by xiaodin1** [comment]
i finally catch the error data, i test this data in local, the program works well and does not throw that exception, the data as follows:
`post_args {
    values {
      key: "\357\277\275\357\277\275opG\357\277\2750*\357\277\275\357\277\275@\357\277\275\357\277\275\357\277\275\357\277\275q\022_\357\277\275\322\257u\357\277\275\357\277\275QaUL\357\277\275\357\277\275\355\232\246\357\277\275O]\357\277\275{U\357\277\275Oi<\314\252\357\277\275k\357\277\275<\357\277\275\357\277\275[2\357\277\275\357\277\275\357\277\275\357\277\275\357\277\275\327\204\357\277\275}W\357\277\275\177\357\277\275,\357\277\275\357\277\275\032\357\277\275\335\246!\357\277\275)\357\277\275\357\277\2752\357\277\2750)\357\277\275\357\277\275Fq\357\277\275\357\277\275 \357\277\275\357\277\275\357\277\275t(\357\277\275|:\357\277\275:M\357\277\275]\357\277\275#\357\277\275\357\277\2750\357\277\275\357\277\275b\"9#\357\277\275[Q 1\357\277\275F\357\277\275\034 q\357\277\275\357\277\275\002\000\357\277\275B\357\277\275\vw\357\277\275,\343\234\200\357\277\275\357\277\275\357\277\275?\357\277\275\357\277\275\357\277\275-m\357\277\275\034\357\277\275o\357\277\275\357\277\2752\030*_\357\277\275\357\277\275\357\277\275\357\277\275*\357\277\275\357\277\275\'\357\277\275\357\277\275\357\277\275\005\023$\311\274n\323\244\357\277\275]\357\277\275P\357\277\275\"\357\277\275\357\277\275\357\277\275j\357\277\275j\357\277\275_\357\277\275\357\277\275TCVu\357\277\275\032\357\277\275\337\274rex\357\277\275\357\277\275\357\277\275,\020\357\277\275M\357\277\275)\357\277\275Bb\357\277\275\357\277\275\357\277\275a\025\021b\357\277\275\357\277\2756\357\277\275\357\277\275\357\277\275X\357\277\275,\357\277\275\357\277\275\357\277\275\\\f\037\357\277\275\357\277\275\024N!\357\277\275\004vi\357\277\275\357\277\275 \030L\357\277\275\357\277\275\025\357\277\275@\357\277\275u\357\277\275\357\277\275D]\357\277\275I:\357\277\275\003\357\277\275\"\357\277\275%\030\032\357\277\275\024\357\277\2753\005~FE\357\277\275{*\357\277\275\357\277\275D\357\277\275\357\277\275\357\277\275\357\277\275"
      value {
        values: "W?~J\005???r???m????2?\000~?\034G\003??<?*?U\020?\\????M??4??? ?@\022$V\001\034?A\031~x\vR1?S?h\036?O?M???\vW??\017?\'6\\??S\003yYP \000?p???6??6??u6.\036???\fCr??mH??Y??(?\022T?\'\'???"
      }
    }
    values {
      key: "?\034#\020\034\357\277\275n\357\277\275\357\277\275K\357\277\275\357\277\275\357\277\275\357\277\275\021\357\277\275\357\277\275w\357\277\275\357\277\275\0357l\357\277\275\357\277\275$\357\277\275\\\357\277\275x\357\277\275H\357\277\275\357\277\275\357\277\275~\357\277\275\357\277\275\357\277\275Hr\357\277\275\b,\357\277\275\357\277\275\030\357\277\275\v|\024\357\277\275\357\277\275)8{sp\357\277\275O\357\277\275S\357\277\275\035\357\277\275\357\277\275\357\277\2759\005\357\277\275\036?\357\277\275z.\357\277\275/\357\277\275"
      value {
        values: "?g??\005\032\vw?????D?i??/?`o??O????\037?8\034?!???????A7\017?W\035?Q??W??w?W?m\035?W=???T??0?\037?-?G:?\vy???D??\034Q?\034\027K?@K{?\f?C??\\\034??$??W??;??j??_Z?z?y??2?\t?x??\020???????i?1??_o\0310k\030@0000795feae07061622c288779d7886b01228f4e4f649ad02f73ec32c6de0000\030 08ac1fc165cbb19eb09af26a38c86cb9\025\000\000"
      }
    }
  }`

**Comment by xiaodin1** [comment]
how to solve（eliminate） this warning?

**Comment by xfxyjwf** [comment]
The content of the proto does look like it's corrupted. I think you need to double check whether the content is what you expected and probably need to fix the conversion mistake that has produced this corrupted data.

**Comment by xiaodin1** [comment]
Protobuf is able to support a variety of encoding format bytes data? In my project we have to deal with GBK, UTF-8, UTF16, gb2312 etc. encoding format data, now I put these data directly into pb, without any processing, execute data.build (). ToByteArray (); method, and sometimes we get the error we discussed above,How should I deal with this situation?

**Comment by xfxyjwf** [comment]
You are not putting GBK or UTF-8 or gb2312 data into protobuf. You are putting a Java String object into protobuf and a Java String is UTF-16. This Java String object is malformed and need to be fixed. If it's converted from some other source, please check your convention methods and the data source. Or you can ignore the warning and proceed at your own risk (like the warning suggests a data loss is guaranteed).

**Comment by xiaodin1** [comment]
thanks！！！
I forgot to reply to you for long time. I finally solved the problem. As you said, I didn't handle the strings that contained the abnormal characters when parsing the post parameters. These strings were placed in the pb data so that the pb object could not be serialized to byte array properly.
