### ISSUE TITLE
Broken Python protobuf==3.5.1 library

### ISSUE THREAD

**Issue by sevaivanov** [google/protobuf#4272]
`rrt protobuf $ pip3.5 freeze | grep proto
protobuf==3.5.1`

Error:
```
/usr/lib64/python3.5/site-packages/google/protobuf/descriptor.py in __new__(cls, name, package, options, serialized_pb, dependencies, public_dependencies, syntax, pool)
    827         # TODO(amauryfa): use the pool passed as argument. This will work only
    828         # for C++-implemented DescriptorPools.
--> 829         return _message.default_pool.AddSerializedFile(serialized_pb)
    830       else:
    831         return super(FileDescriptor, cls).__new__(cls)

TypeError: expected bytes, str found
```

I see that the line causing the below error with the latest version is still in source code at: https://github.com/google/protobuf/blob/master/python/google/protobuf/descriptor.py#L827

**Comment by anandolee** [comment]
Can you let us know how to reproduce the error?

**Comment by sevaivanov** [comment]
Thank you for getting back on this matter.
Please, see below the steps to reproduce as well as system & library information.

Kind regards,
Seva
```
rrt protobuf $ cat message.proto
syntax = "proto2";

package kittens;

message MapKittensToDogs {
  optional int32 key = 1;
  optional bytes value = 2;
}
rrt protobuf $ cat test.py 
#!/usr/bin/python3.5

from google import protobuf

from message_pb2 import *

msg = msgStruct()

print(msg.SerializeToString())

rrt protobuf $ protoc -I . --python_out=. message.proto

rrt protobuf $ ./test.py 
Traceback (most recent call last):
  File "./test.py", line 5, in <module>
    from message_pb2 import *
  File "/home/rrt/funtimes/protobuf/message_pb2.py", line 16, in <module>
    serialized_pb='\n\rmessage.proto\x12\x07kittens\".\n\x10MapKittensToDogs\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\r\n\x05value\x18\x02 \x01(\x0c')
  File "/usr/lib64/python3.5/site-packages/google/protobuf/descriptor.py", line 829, in __new__
    return _message.default_pool.AddSerializedFile(serialized_pb)
TypeError: expected bytes, str found

rrt protobuf $ uname -r
3.10.0-514.26.2.el7.x86_64

rrt protobuf $ cat /etc/*elease
CentOS Linux release 7.3.1611 (Core) 

rrt protobuf $ pip3.5 freeze | grep proto
protobuf==3.5.1
```

**Comment by takeda** [comment]
Just FYI, I received similar error when trying to make `riak` package to work with latest `protobuf`. In my case I did not care about a proper fix because that code is deprecated.

I was getting the same issues on Python 3, because in latest version of protobuf, the string is expected to be bytes:

e.g.
```python
serialized_pb='\n\rmessage.proto\x12\x07kittens\".\n\x10MapKittensToDog[...]
```

changing it to:
```python
serialized_pb=b'\n\rmessage.proto\x12\x07kittens\".\n\x10MapKittensToDog[...]
```

Got rid of the error. It looks like the issue is that the `protoc` is (or in version 2.x was) saving the binary data as a string instead of bytes. If current `protoc` doesn't do that (I did not check) then perhaps @sevaivanov is using old `protoc`.

**Comment by overflowcrash** [comment]
@takeda Thank you for your valuable input!

I went ahead and compiled the most recent protoc on centos7 to try it out:
```
rrt protobuf $ cat msg.proto 
syntax = "proto2";

package kittens;

message MapKittensToDogs {
  optional int32 key = 1;
  optional bytes value = 2;
}
rrt protobuf $ cat msg.py 
#!/usr/bin/python3.5

from google import protobuf

from msg_pb2 import *

msg = MapKittensToDogs()

print(msg.SerializeToString())
rrt protobuf $ protoc --version
libprotoc 2.5.0
rrt protobuf $ src/protoc --version
libprotoc 3.6.1
rrt protobuf $ pip3.5 freeze | grep protobuf==
protobuf==3.6.1
rrt protobuf $ src/protoc -I . --python_out=. msg.proto 
rrt protobuf $ ./msg.py
b''
```
You are completely right! However, it is certainly a python library issue because the python packages of 2.5.0 are available for python 3.5 and yet they have python 2 code:
```
rrt protobuf $ sudo pip3.5 install protobuf==2.5.0
Collecting protobuf==2.5.0
  Using cached https://files.pythonhosted.org/packages/3f/ad/c8221a0778cc04197047f0f6ddee683ef1a0851976a4bd4ad17af19d22ec/protobuf-2.5.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-f6ra2ott/protobuf/setup.py", line 52
        print "Generating %s..." % output
                               ^
    SyntaxError: Missing parentheses in call to 'print'
    
    ----------------------------------------
```

I would suggest to simply backport the newer protobuf library to cast a string into bytes for backward compatibility and remove the "supported" python 3+ version for python 2 protobuf libraries in pip which is even more confusing... Upgrading for the most recent libprotoc is not an option considering that the grand majority of enterprises are using the stable Centos versions with their libaries like the 7 which do not package the most recent protobuf libraries.

cheers,
seva

**Comment by takeda** [comment]
You should not use Python that comes with the system, there is a lot of other issues.

I highly recommend to use [IUS Repo](https://ius.io/), then create virtualenv and you have full control over your deependencies.

The IUS repo contains all Python versions up to 3.6 and soon it will have 3.7.

**Comment by anandolee** [comment]
Looks like this has resolved. Feel free to reopen it is still an issue for our new versions
