### ISSUE TITLE
Indentation/syntax error in BUILD bazel file?

### ISSUE THREAD

**Issue by jtattermusch** [google/protobuf#4668]
I'm getting this when running "bazel query" on protobuf's BUILD file.
```
......................
ERROR: /tmpfs/src/github/grpc/third_party/protobuf/BUILD:71:2: indentation error
ERROR: /tmpfs/src/github/grpc/third_party/protobuf/BUILD:68:36: syntax error at ',': expected :
ERROR: /tmpfs/src/github/grpc/third_party/protobuf/BUILD:69:5: Traceback (most recent call last):
	File "/tmpfs/src/github/grpc/third_party/protobuf/BUILD", line 55
		select({":android": [], ":msvc": [], "-..."]})
	File "/tmpfs/src/github/grpc/third_party/protobuf/BUILD", line 69, in select
		$error$
contains syntax error(s)
ERROR: /tmpfs/src/github/grpc/third_party/protobuf/BUILD:113:16: Traceback (most recent call last):
	File "/tmpfs/src/github/grpc/third_party/protobuf/BUILD", line 82
		cc_library(name = "protobuf_lite", srcs = ["s..."], <5 more arguments>)
	File "/tmpfs/src/github/grpc/third_party/protobuf/BUILD", line 113, in cc_library
		LINK_OPTS
name 'LINK_OPTS' is not defined
ERROR: /tmpfs/src/github/grpc/third_party/protobuf/BUILD:180:16: Traceback (most recent call last):
	File "/tmpfs/src/github/grpc/third_party/protobuf/BUILD", line 117
		cc_library(name = "protobuf", srcs = ["src/go..."], <6 more arguments>)
	File "/tmpfs/src/github/grpc/third_party/protobuf/BUILD", line 180, in cc_library
		LINK_OPTS
name 'LINK_OPTS' is not defined
ERROR: /tmpfs/src/github/grpc/third_party/protobuf/BUILD:380:16: Traceback (most recent call last):
	File "/tmpfs/src/github/grpc/third_party/protobuf/BUILD", line 290
		cc_library(name = "protoc_lib", srcs = ["src/..."], <5 more arguments>)
	File "/tmpfs/src/github/grpc/third_party/protobuf/BUILD", line 380, in cc_library
		LINK_OPTS
name 'LINK_OPTS' is not defined
ERROR: /tmpfs/src/github/grpc/third_party/protobuf/BUILD:388:16: Traceback (most recent call last):
	File "/tmpfs/src/github/grpc/third_party/protobuf/BUILD", line 385
		cc_binary(name = "protoc", srcs = ["src/goog..."], <3 more arguments>)
	File "/tmpfs/src/github/grpc/third_party/protobuf/BUILD", line 388, in cc_binary
		LINK_OPTS
name 'LINK_OPTS' is not defined
ERROR: /tmpfs/src/github/grpc/third_party/protobuf/BUILD:591:16: Traceback (most recent call last):
	File "/tmpfs/src/github/grpc/third_party/protobuf/BUILD", line 502
		cc_test(name = "protobuf_test", srcs = (CO..."]), <5 more arguments>)
	File "/tmpfs/src/github/grpc/third_party/protobuf/BUILD", line 591, in cc_test
		LINK_OPTS
name 'LINK_OPTS' is not defined
```

**Comment by jtattermusch** [comment]
Looks like unpaired `]` added in https://github.com/google/protobuf/pull/3984/files?

**Comment by jtattermusch** [comment]
@xfxyjwf   https://github.com/google/protobuf/blob/ce57cccef913681c4a2de1c7703a29135df38ba8/BUILD#L69
