### ISSUE TITLE
Cannot import descriptor

### ISSUE THREAD

**Issue by PlasmaSheep** [google/protobuf#574]
I cannot successfully import descriptor.py.

```
$ python
Python 2.7.6 (default, Sep  9 2014, 15:04:36)
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.39)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from google.protobuf import descriptor as _descriptor
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/protobuf-2.6.1-py2.7.egg/google/protobuf/descriptor.py", line 50, in <module>
    from google.protobuf.pyext import _message
ImportError: cannot import name _message
>>> ^D
$ protoc --version
libprotoc 2.6.1
```

Running on OSX 10.10.

**Comment by PlasmaSheep** [comment]
Fixed.

```
$ pip uninstall protobuf
$ brew install protobuf
$ mkdir -p /Users/alexeibendebury/Library/Python/2.7/lib/python/site-packages
$ echo 'import site; site.addsitedir("/usr/local/lib/python2.7/site-packages")' >> /Users/alexeibendebury/Library/Python/2.7/lib/python/site-packages/homebrew.pth
```

**Comment by ahmaurya** [comment]
Thanks PlasmaSheep. You solved my protobuf problem for both caffe and tensorflow.

**Comment by chrisabrams** [comment]
This fixed the issue for me as well.

**Comment by sara-eb** [comment]
@abendebury  I have installed protobuf 2.6.0 on ubuntu. I have compiled the protobuf source in this directory `/home/user/softwares/code/protobuf-2.6.0` with the default configuration. I have compiled and installed caffe successfully, but I am facing with an error once I want to import it into python.
```
>>> import caffe
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "caffe/__init__.py", line 1, in <module>
    from .pycaffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, RMSPropSolver, AdaDeltaSolver, AdamSolver
  File "caffe/pycaffe.py", line 15, in <module>
    import caffe.io
  File "caffe/io.py", line 8, in <module>
    from caffe.proto import caffe_pb2
  File "caffe/proto/caffe_pb2.py", line 9, in <module>
    from google.protobuf import reflection as _reflection
  File "/home/user/.local/lib/python2.7/site-packages/google/protobuf/reflection.py", line 70, in <module>
    from google.protobuf.internal import python_message
  File "/home/user/.local/lib/python2.7/site-packages/google/protobuf/internal/python_message.py", line 82, in <module>
    from google.protobuf import text_format
  File "/home/user/.local/lib/python2.7/site-packages/google/protobuf/text_format.py", line 630
    if o == 10: return rb"\n"   # optional escape
                            ^
SyntaxError: invalid syntax
```

Do you have any suggestion how to solve this issue `SyntaxError: invalid syntax`? Thanks

**Comment by abendebury** [comment]
@sara-eb: seems like an unrelated problem, you should open a new issue or try stackoverflow

**Comment by sara-eb** [comment]
@abendebury I deleted my question from here. Thank you
