### ISSUE TITLE
How to check protobuf module install successfully

### ISSUE THREAD

**Issue by caxton** [google/protobuf#724]
I have followed the instructions to setup and install python protobuf module, but I still got error:   

File "motiondata_pb2.py", line 4, in <module>
    from google.protobuf import descriptor as _descriptor
ImportError: No module named 'google'

My python version is 3.4, and here is the installation log:

python setup.py build

running build
running build_py
Generating google/protobuf/map_unittest_pb2.py...
google/protobuf/map_unittest.proto:31:10: Unrecognized syntax identifier "proto3".  This parser only recognizes "proto2".

python setup.py test

running test
running egg_info
writing requirements to protobuf.egg-info/requires.txt
writing dependency_links to protobuf.egg-info/dependency_links.txt
writing protobuf.egg-info/PKG-INFO
writing namespace_packages to protobuf.egg-info/namespace_packages.txt
writing top-level names to protobuf.egg-info/top_level.txt
reading manifest file 'protobuf.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no previously-included files found matching 'google/protobuf/internal/*_pb2.py'
warning: no previously-included files found matching 'google/protobuf/internal/*.proto'
warning: no previously-included files matching '*_test.py' found under directory 'google'
warning: no previously-included files matching '*_test.proto' found under directory 'google'
warning: no previously-included files matching 'unittest*_pb2.py' found under directory 'google'
warning: no previously-included files matching '*.dll' found anywhere in distribution
warning: no previously-included files matching '*.pyc' found anywhere in distribution
warning: no previously-included files matching '*.pyo' found anywhere in distribution
warning: no previously-included files matching '*.so' found anywhere in distribution
writing manifest file 'protobuf.egg-info/SOURCES.txt'
running build_ext
Traceback (most recent call last):
  File "setup.py", line 194, in <module>
    ext_modules=ext_module_list,
  File "/usr/lib/python3.4/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.4/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.4/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/lib/python3/dist-packages/setuptools/command/test.py", line 135, in run
    self.with_project_on_sys_path(self.run_tests)
  File "/usr/lib/python3/dist-packages/setuptools/command/test.py", line 116, in with_project_on_sys_path
    func()
  File "/usr/lib/python3/dist-packages/setuptools/command/test.py", line 160, in run_tests
    testLoader = cks
  File "/usr/lib/python3.4/unittest/main.py", line 92, in __init__
    self.parseArgs(argv)
  File "/usr/lib/python3.4/unittest/main.py", line 139, in parseArgs
    self.createTests()
  File "/usr/lib/python3.4/unittest/main.py", line 146, in createTests
    self.module)
  File "/usr/lib/python3.4/unittest/loader.py", line 146, in loadTestsFromNames
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/usr/lib/python3.4/unittest/loader.py", line 146, in <listcomp>
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/usr/lib/python3.4/unittest/loader.py", line 117, in loadTestsFromName
    return self.loadTestsFromModule(obj)
  File "/usr/lib/python3/dist-packages/setuptools/command/test.py", line 36, in loadTestsFromModule
    tests.append(self.loadTestsFromName(submodule))
  File "/usr/lib/python3.4/unittest/loader.py", line 114, in loadTestsFromName
    parent, obj = obj, getattr(obj, part)
AttributeError: 'module' object has no attribute 'text_format_test'

sudo python setup.py install

running install
Checking .pth file support in /usr/local/lib/python3.4/dist-packages/
/usr/bin/python -E -c pass
TEST PASSED: /usr/local/lib/python3.4/dist-packages/ appears to support .pth files
running bdist_egg
running egg_info
writing namespace_packages to protobuf.egg-info/namespace_packages.txt
writing protobuf.egg-info/PKG-INFO
writing dependency_links to protobuf.egg-info/dependency_links.txt
writing requirements to protobuf.egg-info/requires.txt
writing top-level names to protobuf.egg-info/top_level.txt
reading manifest file 'protobuf.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no previously-included files found matching 'google/protobuf/internal/*_pb2.py'
warning: no previously-included files found matching 'google/protobuf/internal/*.proto'
warning: no previously-included files matching '*_test.py' found under directory 'google'
warning: no previously-included files matching '*_test.proto' found under directory 'google'
warning: no previously-included files matching 'unittest*_pb2.py' found under directory 'google'
warning: no previously-included files matching '*.dll' found anywhere in distribution
warning: no previously-included files matching '*.pyc' found anywhere in distribution
warning: no previously-included files matching '*.pyo' found anywhere in distribution
warning: no previously-included files matching '*.so' found anywhere in distribution
writing manifest file 'protobuf.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
Generating google/protobuf/map_unittest_pb2.py...
google/protobuf/map_unittest.proto:31:10: Unrecognized syntax identifier "proto3".  This parser only recognizes "proto2".

**Comment by xfxyjwf** [comment]
The error message suggests you are using an older version protoc.
```
Unrecognized syntax identifier "proto3". This parser only recognizes "proto2".
```
Try follow the C++ instructions to build and install proto C++ first.

**Comment by caxton** [comment]
@xfxyjwf 

The protoc version is 2.5.0 however?

% protoc --version
libprotoc 2.5.0

**Comment by dano** [comment]
@caxton Do you still see the decoding error on the latest master?

**Comment by caxton** [comment]
@dano No, the issue should be fixed. Thank you.

**Comment by caxton** [comment]
update "./setup.py test" results based on latest master

======================================================================
ERROR: testParseBadExtension (google.protobuf.internal.text_format_test.Proto2Tests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/protobuf-3.0.0a4-py3.4.egg/google/protobuf/internal/text_format_test.py", line 632, in testParseBadExtension
    six.assertRaisesRegex(self,
AttributeError: 'module' object has no attribute 'assertRaisesRegex'

======================================================================
ERROR: testParseDuplicateExtensionScalars (google.protobuf.internal.text_format_test.Proto2Tests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/protobuf-3.0.0a4-py3.4.egg/google/protobuf/internal/text_format_test.py", line 656, in testParseDuplicateExtensionScalars
    six.assertRaisesRegex(self,
AttributeError: 'module' object has no attribute 'assertRaisesRegex'

======================================================================
ERROR: testParseDuplicateNestedMessageScalars (google.protobuf.internal.text_format_test.Proto2Tests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/protobuf-3.0.0a4-py3.4.egg/google/protobuf/internal/text_format_test.py", line 667, in testParseDuplicateNestedMessageScalars
    six.assertRaisesRegex(self,
AttributeError: 'module' object has no attribute 'assertRaisesRegex'

======================================================================
ERROR: testParseDuplicateScalars (google.protobuf.internal.text_format_test.Proto2Tests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/protobuf-3.0.0a4-py3.4.egg/google/protobuf/internal/text_format_test.py", line 677, in testParseDuplicateScalars
    six.assertRaisesRegex(self,
AttributeError: 'module' object has no attribute 'assertRaisesRegex'

======================================================================
ERROR: testParseGroupNotClosed (google.protobuf.internal.text_format_test.Proto2Tests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/protobuf-3.0.0a4-py3.4.egg/google/protobuf/internal/text_format_test.py", line 686, in testParseGroupNotClosed
    six.assertRaisesRegex(self,
AttributeError: 'module' object has no attribute 'assertRaisesRegex'

======================================================================
ERROR: testParseBadEnumValue5469cba0515211e5a79b70f395157b1d0 (google.protobuf.internal.text_format_test.TextFormatTest)
testParseBadEnumValue(<module 'google.protobuf.unittest_pb2' from '/usr/local/lib/python3.4/dist-packages/protobuf-3.0.0a4-py3.4.egg/google/protobuf/unittest_pb2.py'>)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/protobuf-3.0.0a4-py3.4.egg/google/protobuf/internal/_parameterized.py", line 230, in BoundParamTest
    test_method(self, testcase_params)
  File "/usr/local/lib/python3.4/dist-packages/protobuf-3.0.0a4-py3.4.egg/google/protobuf/internal/text_format_test.py", line 321, in testParseBadEnumValue
    six.assertRaisesRegex(self,
AttributeError: 'module' object has no attribute 'assertRaisesRegex'

======================================================================
ERROR: testParseBadEnumValue5469cba0515211e5a79b70f395157b1d1 (google.protobuf.internal.text_format_test.TextFormatTest)
testParseBadEnumValue(<module 'google.protobuf.unittest_proto3_arena_pb2' from '/usr/local/lib/python3.4/dist-packages/protobuf-3.0.0a4-py3.4.egg/google/protobuf/unittest_proto3_arena_pb2.py'>)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/protobuf-3.0.0a4-py3.4.egg/google/protobuf/internal/_parameterized.py", line 230, in BoundParamTest
    test_method(self, testcase_params)
  File "/usr/local/lib/python3.4/dist-packages/protobuf-3.0.0a4-py3.4.egg/google/protobuf/internal/text_format_test.py", line 321, in testParseBadEnumValue
    six.assertRaisesRegex(self,
AttributeError: 'module' object has no attribute 'assertRaisesRegex'

======================================================================
ERROR: testParseBadIntValue5469cba0515211e5a79b70f395157b1d0 (google.protobuf.internal.text_format_test.TextFormatTest)
testParseBadIntValue(<module 'google.protobuf.unittest_pb2' from '/usr/local/lib/python3.4/dist-packages/protobuf-3.0.0a4-py3.4.egg/google/protobuf/unittest_pb2.py'>)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/protobuf-3.0.0a4-py3.4.egg/google/protobuf/internal/_parameterized.py", line 230, in BoundParamTest
    test_method(self, testcase_params)
  File "/usr/local/lib/python3.4/dist-packages/protobuf-3.0.0a4-py3.4.egg/google/protobuf/internal/text_format_test.py", line 338, in testParseBadIntValue
    six.assertRaisesRegex(self,
AttributeError: 'module' object has no attribute 'assertRaisesRegex'

======================================================================
ERROR: testParseBadIntValue5469cba0515211e5a79b70f395157b1d1 (google.protobuf.internal.text_format_test.TextFormatTest)
testParseBadIntValue(<module 'google.protobuf.unittest_proto3_arena_pb2' from '/usr/local/lib/python3.4/dist-packages/protobuf-3.0.0a4-py3.4.egg/google/protobuf/unittest_proto3_arena_pb2.py'>)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/protobuf-3.0.0a4-py3.4.egg/google/protobuf/internal/_parameterized.py", line 230, in BoundParamTest
    test_method(self, testcase_params)
  File "/usr/local/lib/python3.4/dist-packages/protobuf-3.0.0a4-py3.4.egg/google/protobuf/internal/text_format_test.py", line 338, in testParseBadIntValue
    six.assertRaisesRegex(self,
AttributeError: 'module' object has no attribute 'assertRaisesRegex'

======================================================================
ERROR: testParseSingleWord5469cba0515211e5a79b70f395157b1d0 (google.protobuf.internal.text_format_test.TextFormatTest)
testParseSingleWord(<module 'google.protobuf.unittest_pb2' from '/usr/local/lib/python3.4/dist-packages/protobuf-3.0.0a4-py3.4.egg/google/protobuf/unittest_pb2.py'>)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/protobuf-3.0.0a4-py3.4.egg/google/protobuf/internal/_parameterized.py", line 230, in BoundParamTest
    test_method(self, testcase_params)
  File "/usr/local/lib/python3.4/dist-packages/protobuf-3.0.0a4-py3.4.egg/google/protobuf/internal/text_format_test.py", line 303, in testParseSingleWord
    six.assertRaisesRegex(self,
AttributeError: 'module' object has no attribute 'assertRaisesRegex'

======================================================================
ERROR: testParseSingleWord5469cba0515211e5a79b70f395157b1d1 (google.protobuf.internal.text_format_test.TextFormatTest)
testParseSingleWord(<module 'google.protobuf.unittest_proto3_arena_pb2' from '/usr/local/lib/python3.4/dist-packages/protobuf-3.0.0a4-py3.4.egg/google/protobuf/unittest_proto3_arena_pb2.py'>)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/protobuf-3.0.0a4-py3.4.egg/google/protobuf/internal/_parameterized.py", line 230, in BoundParamTest
    test_method(self, testcase_params)
  File "/usr/local/lib/python3.4/dist-packages/protobuf-3.0.0a4-py3.4.egg/google/protobuf/internal/text_format_test.py", line 303, in testParseSingleWord
    six.assertRaisesRegex(self,
AttributeError: 'module' object has no attribute 'assertRaisesRegex'

======================================================================
ERROR: testParseUnknownField5469cba0515211e5a79b70f395157b1d0 (google.protobuf.internal.text_format_test.TextFormatTest)
testParseUnknownField(<module 'google.protobuf.unittest_pb2' from '/usr/local/lib/python3.4/dist-packages/protobuf-3.0.0a4-py3.4.egg/google/protobuf/unittest_pb2.py'>)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/protobuf-3.0.0a4-py3.4.egg/google/protobuf/internal/_parameterized.py", line 230, in BoundParamTest
    test_method(self, testcase_params)
  File "/usr/local/lib/python3.4/dist-packages/protobuf-3.0.0a4-py3.4.egg/google/protobuf/internal/text_format_test.py", line 312, in testParseUnknownField
    six.assertRaisesRegex(self,
AttributeError: 'module' object has no attribute 'assertRaisesRegex'

======================================================================
ERROR: testParseUnknownField5469cba0515211e5a79b70f395157b1d1 (google.protobuf.internal.text_format_test.TextFormatTest)
testParseUnknownField(<module 'google.protobuf.unittest_proto3_arena_pb2' from '/usr/local/lib/python3.4/dist-packages/protobuf-3.0.0a4-py3.4.egg/google/protobuf/unittest_proto3_arena_pb2.py'>)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/protobuf-3.0.0a4-py3.4.egg/google/protobuf/internal/_parameterized.py", line 230, in BoundParamTest
    test_method(self, testcase_params)
  File "/usr/local/lib/python3.4/dist-packages/protobuf-3.0.0a4-py3.4.egg/google/protobuf/internal/text_format_test.py", line 312, in testParseUnknownField
    six.assertRaisesRegex(self,
AttributeError: 'module' object has no attribute 'assertRaisesRegex'

======================================================================
ERROR: testParsingFlatClassWithExplicitClassDeclaration (google.protobuf.internal.reflection_test.ClassAPITest)
Test that the generated class can parse a flat message.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/protobuf-3.0.0a4-py3.4.egg/google/protobuf/internal/reflection_test.py", line 2925, in testParsingFlatClassWithExplicitClassDeclaration
    class MessageClass(six.with_metaclass(reflection.GeneratedProtocolMessageType, message.Message)):
  File "/usr/lib/python3/dist-packages/six.py", line 617, in with_metaclass
    return meta("NewBase", bases, {})
  File "/usr/local/lib/python3.4/dist-packages/protobuf-3.0.0a4-py3.4.egg/google/protobuf/internal/python_message.py", line 131, in __new__
    descriptor = dictionary[GeneratedProtocolMessageType._DESCRIPTOR_KEY]
KeyError: 'DESCRIPTOR'

======================================================================
ERROR: testDescriptorProtoSupport (google.protobuf.internal.reflection_test.ReflectionTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/protobuf-3.0.0a4-py3.4.egg/google/protobuf/internal/reflection_test.py", line 1066, in testDescriptorProtoSupport
    class CarMessage(six.with_metaclass(reflection.GeneratedProtocolMessageType, message.Message)):
  File "/usr/lib/python3/dist-packages/six.py", line 617, in with_metaclass
    return meta("NewBase", bases, {})
  File "/usr/local/lib/python3.4/dist-packages/protobuf-3.0.0a4-py3.4.egg/google/protobuf/internal/python_message.py", line 131, in __new__
    descriptor = dictionary[GeneratedProtocolMessageType._DESCRIPTOR_KEY]
KeyError: 'DESCRIPTOR'

======================================================================
ERROR: testHandWrittenReflection (google.protobuf.internal.reflection_test.ReflectionTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/protobuf-3.0.0a4-py3.4.egg/google/protobuf/internal/reflection_test.py", line 1019, in testHandWrittenReflection
    class MyProtoClass(six.with_metaclass(reflection.GeneratedProtocolMessageType, message.Message)):
  File "/usr/lib/python3/dist-packages/six.py", line 617, in with_metaclass
    return meta("NewBase", bases, {})
  File "/usr/local/lib/python3.4/dist-packages/protobuf-3.0.0a4-py3.4.egg/google/protobuf/internal/python_message.py", line 131, in __new__
    descriptor = dictionary[GeneratedProtocolMessageType._DESCRIPTOR_KEY]
KeyError: 'DESCRIPTOR'

----------------------------------------------------------------------

**Comment by orenov** [comment]
I observe the same issue on my linux(ubuntu). 
C++ installation pass all test.
While testing on darwin i got no errors.
Any updates?

**Comment by xfxyjwf** [comment]
The tests are using a newer version of six. Try upgrading the six module.
