### ISSUE TITLE
NPE: GeneratedMessageLite.getParserForType

### ISSUE THREAD

**Issue by AlexanderShniperson** [google/protobuf#833]
Hi folks.

This happens:

```
java.lang.NullPointerException
        at com.google.protobuf.GeneratedMessageLite.getParserForType(GeneratedMessageLite.java:93)
        at ProtoMessages.MessageRequestBase$MessageRequest.parser(MessageRequestBase.java:410)
        at ProtoMessages.MessageRequestBase$MessageRequest.parseFrom(MessageRequestBase.java:200)
        at net.orionlab.brr.CommunicationMessage.BinarySerializer$.Deserialize(BinarySerializer.scala:34)
        at net.orionlab.brr.actors.SocketClientActor$SocketClientActor$$anonfun$receive$1.applyOrElse(SocketClientActor.scala:46)
        at akka.actor.Actor$class.aroundReceive(Actor.scala:467)
        at net.orionlab.brr.actors.SocketClientActor$SocketClientActor.aroundReceive(SocketClientActor.scala:23)
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
        at akka.actor.ActorCell.invoke(ActorCell.scala:487)
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:254)
        at akka.dispatch.Mailbox.run(Mailbox.scala:221)
        at akka.dispatch.Mailbox.exec(Mailbox.scala:231)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
]]
```

when i try to parse my message from byte array like this:
MessageRequest.parseFrom( byte_array_message )

used fresh commit: 0e5686a70768a289782eb1e1aa86646e56897e4d

**Comment by xfxyjwf** [comment]
Are you using the same version of protoc with the Java runtime? (if you are using a version on github you will need to compile the protoc from source of the same version).

**Comment by AlexanderShniperson** [comment]
yes i build protoc from the source, something broken at the source

**Comment by xfxyjwf** [comment]
Could you also post the content of your proto definition and the Java code that can reproduce this failure?

**Comment by AlexanderShniperson** [comment]
hi, yes i can give you proto files, but i dont want to return back to unworkable version of the source and generate java files
```
syntax = "proto2";
option optimize_for = LITE_RUNTIME;
option java_package = "ProtoMessages";
option java_outer_classname = "CommunicationMessageTypeBase";

enum eCommunicationMessageType {
cmtNone = 0;
cmtCheckAPIVersion = 1; // check actual api version
cmtAuth = 2; // auth user
}
```
```
syntax = "proto2";

import "CommunicationMessageType.proto";

option optimize_for = LITE_RUNTIME;
option java_package = "ProtoMessages";
option java_outer_classname = "MessageRequestBase";

message MessageRequest {
required eCommunicationMessageType messageType = 1 [default = cmtNone];
required bytes messageBody = 2 [default = "\0"];
}
```

**Comment by TeBoring** [comment]
Close this for cleanup. Feel free to reopen it if there is still problem.
