### ISSUE TITLE
How to use 'Any' type in Python

### ISSUE THREAD

**Issue by hhzzk** [google/protobuf#871]
Hi,
In the [document](https://developers.google.com/protocol-buffers/docs/proto3#any),I find there are java and c++ accessors of Any type, java are pack() and unpack(), c++ are PackFrom() and PackTo(), but no python's. And I want to use Any type in python,

My program like this:
.proto file:
```shell
message HidargsReply {
    google.protobuf.Any hidargs = 1;
}
```
application file:
```python
        _hidargs_tmp = HIDB.get_dict(hid)
        _hidargs = json.dumps(_hidargs_tmp)
        return db_op_pb.HidargsReply(hidargs=_hidargs)
```
*_hidargs_tmp* is a unicode type

With above I got following error:
```python
ERROR:root:Exception during ingestion!
Traceback (most recent call last):
  File "build/bdist.linux-x86_64/egg/grpc/framework/foundation/callable_util.py", line 69, in _call_logging_exceptions
    return _EasyOutcome(Outcome.Kind.RETURNED, behavior(*args, **kwargs), None)
  File "build/bdist.linux-x86_64/egg/grpc/framework/base/_ingestion.py", line 198, in moar
    self._consumer.consume(payload)
  File "build/bdist.linux-x86_64/egg/grpc/framework/foundation/stream_util.py", line 48, in consume
    self._downstream.consume(self._transformation(value))
  File "build/bdist.linux-x86_64/egg/grpc/framework/face/_service.py", line 108, in <lambda>
    lambda request: method(request, rpc_context), response_consumer)
  File "build/bdist.linux-x86_64/egg/grpc/framework/alpha/_face_utilities.py", line 150, in service
    request, _reexport.rpc_context(face_rpc_context))
  File "build/bdist.linux-x86_64/egg/grpc/framework/alpha/utilities.py", line 75, in service_unary_unary
    return self._unary_unary(request, context)
  File "/data/server/servers/q_ops.py", line 42, in HIDB_get_dict
    return db_op_pb.HidargsReply(hidargs=_hidargs)
  File "build/bdist.linux-x86_64/egg/google/protobuf/internal/python_message.py", line 519, in init
    _ReraiseTypeErrorWithFieldName(message_descriptor.name, field_name)
  File "build/bdist.linux-x86_64/egg/google/protobuf/internal/python_message.py", line 450, in _ReraiseTypeErrorWithFieldName
    six.reraise(type(exc), exc, sys.exc_info()[2])
  File "build/bdist.linux-x86_64/egg/google/protobuf/internal/python_message.py", line 517, in init
    copy.MergeFrom(new_val)
  File "build/bdist.linux-x86_64/egg/google/protobuf/internal/python_message.py", line 1208, in MergeFrom
    "expected %s got %s." % (cls.__name__, type(msg).__name__))
TypeError: Parameter to MergeFrom() must be instance of same class: expected Any got str. for field HidargsReply.hidargs
```
 Thanks a lot.

**Comment by anandolee** [comment]
Any accessors for python is under development

**Comment by richburdon** [comment]
Is this still the case?

**Comment by anandolee** [comment]
Any and some other Well Known Types are supported now in Python. You can see well_known_types_test for example usage:
https://github.com/google/protobuf/blob/master/python/google/protobuf/internal/well_known_types_test.py

**Comment by dminkovsky** [comment]
is uint32value implemented yet? can't find it anywhere. thank you.

**Comment by xfxyjwf** [comment]
It's defined here:
https://github.com/google/protobuf/blob/master/src/google/protobuf/wrappers.proto#L91

**Comment by dminkovsky** [comment]
Yes, so in the Python runtime how do I import that message class? Like in
Java I can
com.google.protobuf.UInt32Value.newBuilder().setValue(1).build().toByteArray();
ср, 7 июня 2017 г. в 18:23, Feng Xiao <notifications@github.com>:
